### ISSUE TITLE
Add caching options for array map

### ISSUE THREAD

**Issue by Adlai-Holler** [ReactiveKit/Bond#104]
@srdanrasic Sometimes it's expensive to recreate the value every time its accessed. I'm thinking of something like:

``` swift
enum MapStorageStrategy {
  // immediately computes and stores each mapped value
  case Eager
  // computes each mapped value when requested and stores it indefinitely
  case Lazy
  // never store any mapped values
  case None
}
```

It would be nice to have an invalidation method, but our proxy array classes are currently hidden so that may have to wait. I'm glad to build this if y'all agree it's worth having.

**Comment by ivanmoskalev** [comment]
Awesome :+1: I'd love to have that.

**Comment by srdanrasic** [comment]
I see the potential. Instead of modifying `map`, maybe we could introduce another function `cache` that returns a new `proxy array` that manages caching?

```swift
let images = fileNames.map { UIImage(named: $) }.cache(.Lazy)
```

What do you think?

**Comment by ivanmoskalev** [comment]
@srdanrasic wonderful and abstract: we can have caches not only for arrays.

**Comment by srdanrasic** [comment]
Thanks @ivanmoskalev. I'm working on a next version of Bond with complete architecture redesign that will fix current flaws. It should have much more powerful yet simpler arrays. I'll push it in the development branch in next few days when I refine few details. I'll appreciate any feedback for you or anyone else, if you get some time to review it.

**Comment by srdanrasic** [comment]
Closed as outdated.
