### ISSUE TITLE
CoreData / Realm integration

### ISSUE THREAD

**Issue by srdanrasic** [ReactiveKit/Bond#155]
Ticket to discuss best ways to integrate CoreData / Realm with Bond and how could Bond provide that integration out of the box.

**Comment by tonyxiao** [comment]
I actually implemented CoreData integration for bond v3, working on getting it upgraded to bond v4 at the moment. Take a look (v3 version) https://github.com/tonyxiao/Bond/blob/coredata/Bond/Bond+CoreData.swift

**Comment by tonyxiao** [comment]
My thinking it that we can have a sibling class of `Observable` array (so subclass of `EventProducer<ObservableArrayEvent<Array<ElementType>>>`) that's backed by CoreData / Realm.

**Comment by srdanrasic** [comment]
Something like that sounds about right.

It may be possible to make `NSFetchedController` conform to `SequenceType` protocol and use it as an underlying sequence in events `EventProducer<ObservableArrayEvent<NSFetchedController<ElementType>>>`. There may be few others generalizations necessary, though, if we want to completely avoid any internal conversions to Array.

For example, Table/Collection view extensions require underlying type to be ObservableArray or they will convert it automatically - we should avoid that if we want best performance.

PS. There is a bug #150 in ObservableArray `performBatchUpdates` method when used in conjunction with Table/Collection view. I'm working on it right now...

**Comment by tonyxiao** [comment]
Yea, I started the conversion to v4. I have a version now that compiles but I haven't gotten a chance to actually test it with TableView yet. It's especially not clear to me how to compose multiple `FetchedResultsArray` as sections of a single `Observable` parent array yet. But here's the wip https://github.com/tonyxiao/Bond/blob/master/Bond/Extensions/iOS/CoreData+Bond.swift

**Comment by tempire** [comment]
Any updates on this?

**Comment by sohooo** [comment]
Interested as well if there's a chance CoreData/Realm will be supported.

**Comment by damianesteban** [comment]
Concerning integration with Realm, this library - [RealmResultsController](https://github.com/redbooth/RealmResultsController) - takes an interesting approach.    I'm wondering if something like that could work with Bond.  Going to play around a bit with it tonight and tomorrow.

**Comment by loganallenc** [comment]
I'm also interested in the possibility of CoreData support.

**Comment by MattNewberry** [comment]
+1

**Comment by damianesteban** [comment]
I wonder if this will be easier now that Realm finally has [fine-grained notifications](https://realm.io/news/realm-objc-swift-0.99.0/)?

**Comment by srdanrasic** [comment]
Not planned at the moment.
