### ISSUE TITLE
NSTableView+Bond with tableColumn

### ISSUE THREAD

**Issue by thomjordan** [ReactiveKit/Bond#182]
Here's a slight variation for the NSTableView+Bond extension that adds a `tableColumn` parameter to `createCell()`.

After making these changes to a renamed protocol in a local copy of NSTableView+Bond, I was pleased to find that when using `bindTo()` for binding a datasource to a tableView, simply binding a datasource for each individual column to the same `( tableView, delegate )` pair works perfectly, simply by addressing the columns by their identifier within a `createCell()` implementation.
I've been using this variation for the past two days or so, and everything's working well.

This may be redundant, since I'm not sure if I missed an existing way to bind to multiple columns in an NSTableView. If so, please respond. Also, I'm not sure if this is the appropriate medium for this since I'm not a contributor.  If the issue tracker for Bond is ok with being used similarly to the dev-branch of a mailing list then I'm in the right place I think.

I've been using Bond for about four days now and my whole way of thinking about my project has been revolutionized. Thanks !

``` swift
public protocol BNDTableViewWithColumnDelegate {
    typealias Element
    func createCell(row: Int, tableColumn: NSTableColumn, array: ObservableArray<Element>, tableView: NSTableView) -> NSTableCellView
}

@objc func tableView(tableView: NSTableView, viewForTableColumn tableColumn: NSTableColumn?, row: Int) -> NSView? {
    return delegate?.createCell(row, tableColumn: tableColumn?, array: array, tableView: tableView)
}

column_1_datasource.bindTo( tableView, delegate: viewController )
column_2_datasource.bindTo( tableView, delegate: viewController )
column_3_datasource.bindTo( tableView, delegate: viewController )
column_4_datasource.bindTo( tableView, delegate: viewController )
```

**Comment by srdanrasic** [comment]
Hi @thomjordan,

Only one data source can be bound to a table view. In your example, only `row_4_datasource` would end up being bound to table view. That might work, but if content of other datasources (1-3) changes, those changes would not be propagated the the table view. 

It might be the best not to use NSTableView bindings if you have multiple columns for now. Just setup delegate and data source manually.

I'll see if this can be improved in future.

**Comment by thomjordan** [comment]
Hi Srdan,

 Thanks for the update. I had finally gotten it to work binding to each row
separately using the approach cited above, which surprised me, so after
hearing back from you I went back and double checked everything. It turns
out that (as far as I can tell) it does work binding each row to the same
delegate instance, as long as there is a separately defined datasource for
each row, and any column-specific behavior is isolated within the
createCell() method. I made some minor changes to the
"NSTableView+Bond.swift" file, to add a new column parameter to
createCell() for this purpose. When it came time to do the actual binding
though, I was stumped, because I had a separate 1D datasource for each row,
and I realized that I would have to bind multiple datasources to the same
delegate instance. I was about to give up then when I tried it anyways, and
surprisingly it worked.  This approach is quite brittle though, since it
only seems to work correctly if the datasource, tableView & delegate
components are instantiated in a particular order. I want to do a backtrace
later to see if this is indeed the case.  I spent most of the day yesterday
trying to refactor my code into a better design three separate times,
including using one datasource that hosts model objects with a field for
each column, and in each case the tableView showed unpredictable behavior
immediately when adding rows and the changing the content of the datasource
rows programmatically. After reading your response then it makes more sense
to me now why nothing was working for me yesterday.

The good news is that I just rigorously rechecked the behavior of the
tableView in the particular arrangement that seems to be working for me,
changing content for multiple rows and columns of the datasource within
both single and separate code blocks, and also manually changing various
cell content in the view, and everything is working as expected. I'm only
using the .Update case of the ObservableArray operations, so I'm not sure
if that is a special case or not.  I have no experience with unit testing,
and this looks like a good time to change that. If I can put together a
correct test case in my spare time over the next few days, as soon as I
know one way or another, I'll report back with the relevant info. If I can
confirm that this implementation does indeed work correctly, and if a
particular instantiation sequence contributes to that, I'll include a more
complete example that can be reproduced.

Best,
Thom

**Comment by thomjordan** [comment]
I'm also comparing Strings instead of objects so this might only work with value types.

**Comment by thomjordan** [comment]
I mistakenly wrote "row" instead of column in the first code example above, and then unconsciously propagated that error in my subsequent comments.  I just went back and updated both comments with the correct info.  The multi-column NSTableView I've been using is working well with a separate datasource for each column.  Sorry for the mixup !

**Comment by lambdaupb** [comment]
This worked for me as well.

Support for multiple Columns in a TableView is kind of essential :)

**Comment by thomjordan** [comment]
Good to hear !  

Have you seen [ReactiveKit](https://github.com/ReactiveKit) yet?  It's Srdan's successor to Bond, I guess.. some of the intro docs explains some of the difference between the two. I've been using that now for a few weeks and have been seeing great results.  The Cocoa version of TableView doesn't address separate columns yet. It probably could be altered in a similar way to Bond. The code for it in ReactiveKit looks very similar.

**Comment by thomjordan** [comment]
[Here's](https://github.com/ReactiveKit/ReactiveKit#threading) the explanation of why a new framework was needed.

**Comment by lambdaupb** [comment]
Hm, looks a lot nicer, especially the ObservableCollections. But I cant find any Cocoa View extensions for OSX yet.
