### ISSUE TITLE
ReactiveKit

### ISSUE THREAD

**Issue by srdanrasic** [ReactiveKit/Bond#200]
Hi Everyone,

Much of you started asking for features that Bond is not really meant to support. Bond was primarily made for UIKit bindings, but with help from the community it grow beyond that, adding AppKit support and taking direction into FRP. There were requests for watchOS, error handling, better KVO and more. 

All that would make Bond too heavy because it doesn't scale properly. I'm, however, on same page as you are so I did that, but differently. With the experience of Bond and knowing its shortcomings I started a new project - [ReactiveKit](https://github.com/ReactiveKit/ReactiveKit). It has what Bond has plus much more. It scales well because UIKit extensions are now separate framework. It supports FRP and error handling for asynchronous tasks through Operation type. Observable is still there. ObservableArray has become ObservableCollection and it now supports arrays, sets and dictionaries. It has much better performance. KVO is now easier and safer. Threading is also enhanced.

Currently there is no AppKit support for OS X. That is planned as a separate framework. There are no batch updates of ObservableCollections yet and no support for multiple sections in table/collection view bindings. On every other aspect - its better. Initial version is on CocoaPods so if you're ready for an adventure, check it out - https://github.com/ReactiveKit/ReactiveKit.

What does this mean for Bond? Well, not much will change. I'll try to keep it simple and focused on UI bindings. It will not go deep into FRP. 

Thanks!

**Comment by tonyarnold** [comment]
I'm happy to help with the AppKit bindings when that project gets going.

**Comment by srdanrasic** [comment]
That's much appreciated @tonyarnold. I'll setup the project within next few days, porting what we currently have, so we have something to start with.

**Comment by ramirez** [comment]
This means that if I need ObservableCollections, which seems it should naturally be a part of bond, I need to buy the whole heavy weight of ReactiveKit, including the promises kit (AKA Operations). Sad.

**Comment by srdanrasic** [comment]
@ramirez, actually, ReactiveKit has less lines of code then Bond and at the same time more features and better performance. So, hmm, no heavy weight.

Framework | Lines of code approx. (CocoaPods stats)
--------------|---------------
ReactiveKit |1900
Bond | 2300
RxSwift | 7800
ReactiveCocoa  | 10400

I've spent significant amount of time trying to make it as lightweight as possible while at the same time solving deficiencies of Bond.

Doing ObservableCollection (among other things) for Bond would introduce significant backward incompatible changes I don't want to introduce so that people can continue using Bond if it's enough for them. Who needs additional staff is welcome to upgrade to ReactiveKit.

**Comment by ramirez** [comment]
Hmm... Ok. I'll try it. I'm also happy to contribute, if needed.

L.

**Comment by srdanrasic** [comment]
@ramirez thanks, that's appreciated.

**Comment by ivanmoskalev** [comment]
@srdanrasic I'll be glad to help with ReactiveKit too. CI / Coverage / Tests as usual :) If you add me to the organization, I'll set it all up.

**Comment by manas-chaudhari** [comment]
@srdanrasic I would love to contribute. Where can I find the roadmap/TODOs? 
Also, I think it would be a good idea to document the shortcomings that you have realised in SwiftBond, and how you have/will overcome them in ReactiveKit.

**Comment by srdanrasic** [comment]
Thanks everyone! TODOs are listed in issues as enhancements - https://github.com/ReactiveKit/ReactiveKit/issues. Feel free to add your own.

**Comment by scisci** [comment]
Would it be possible to outline a migration guide from Bond to ReactiveKit?
