### ISSUE TITLE
Array filter by field

### ISSUE THREAD

**Issue by Evgeniy-Odesskiy** [ReactiveKit/Bond#207]
I have:

``` swift
class Bird: NSObject {
    init(flyable: Bool ) {
        canFly = Dynamic(flyable)
        super.init()
    }
    var canFly: Dynamic<Bool>
}
```

and I have an array of birds

``` swift
var birds = DinamicArray([Bird(true), Bird(true), Bird(true)]).
```

I want get not flyable birds filtered array which automatically update when birds entities canFly modifying.

Something like:

``` swift
public func filterDyn(f: T -> Dynamic<Bool>) -> DynamicArray<T>
var notFlyableBirds = birds.filterDyn({$0.canFly.map({ $0 == false })})
```

I wrote this feature in fork, but I want use Bond without modifying.
https://github.com/Evgeniy-Odesskiy/Bond/blob/master/Bond/Bond%2BArrays.swift
Can I achive this behavior with new Bondv4?

**Comment by srdanrasic** [comment]
I fear that you might unnecessarily overcomplicate your code by doing something like that. You should aim for model objects to be simple structs.

```swift
struct Bird {
  var canFly: Bool
}
```

Then updating the dynamic/observable array like 

```swift
birds[0].canFly = true
```

would send event.

**Comment by Evgeniy-Odesskiy** [comment]
Thank you for the answer.
I tried this approach. Works perfectly with struct.
But I don’t understand why this approach not work with class!

My code:

```swift
class Bird: NSObject {
    init(name: String, canFly: Boo) {
        self.canFly = canFly
        self.name = name
        super.init()
    }
    var canFly: Bool
    var name: String
}

let bird1 = Bird(name: "parrot", canFly: true)
let bird2 = Bird(name: "crow", canFly: true)
       
birds = ObservableArray([bird1, bird2, bird3, bird4])
 birds.filter { $0.canFly == true }.lift().bindTo(tableView, proxyDataSource: self) { indexPath, dataSource, tableView -> UITableViewCell in
   let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath)
   let bird = dataSource[indexPath.section][indexPath.row]
   cell.textLabel?.text = bird.name
   return cell
}

birds[0].canFly = false
```
Not send event.

**Comment by Evgeniy-Odesskiy** [comment]
Thank you for response.
This approach works great!
But my code is reasonable complicated because I need abilities bind to canFly property and filter array by this property. How can I achieve this?
