### ISSUE TITLE
Array.append doesn't trigger observation

### ISSUE THREAD

**Issue by njtuxy** [ReactiveKit/Bond#216]
I am on Xcode 7.1.1

I have tried this example:
var captain = Observable("Jim")
and captain.next("spax") 
and it trigger the observation successfully. 

But also tried Array.append but it never triggered the observation, is there a special way to append new element into an array like 'next' ?

**Comment by srdanrasic** [comment]
Hi @njtuxy, could you post more details about what have you done?

**Comment by njtuxy** [comment]
Sure, 

I use a struct to save an ObservableArray which like this:

#Definition for Contacts:
struct Contacts {
    static var contacts = ObservableArray([Contact]())
}

#Definition for Contact
struct Contact {
    
    let email: String!
    let uid: String!
    
    init(uid: String, email: String){
        self.email = email
        self.uid = uid
    }
}

Then I add an observer in the landing view's viewDidAppear section:

    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
          
	Contacts.contacts.observe{event in
			print(event.sequence)
		}
    }

The result: 
If I update the Array's value from another view(or outside of the app), the obeserver never got triggered.

**Comment by srdanrasic** [comment]
Hi @njtuxy, 

Sorry for not getting back earlier to you... Have you found a solution? This looks very simple and I'm not sure what could go wrong here. Have you check that `viewDidAppear` is getting called? How exactly are you updating contacts array?
