### ISSUE TITLE
How to replace binding?

### ISSUE THREAD

**Issue by ghost** [ReactiveKit/Bond#219]
Hi, I'm trying to change UITextField bindings after user action. Let's imagine situation where user can have on one screen many instances of same "data" which he can switch by button/tabs.

 I have outlet in view controller for UITextfield
 I have properties in view model like:

```
var values = [Observable<String?>]()
values.append(Observable<String?>(""))
values.append(Observable<String?>(""))
```

Then I'm binding textfield and observable and creating observer:

```
let disposable = textfield.bnd_text.bidirectionalBindTo(values[0])
let obsDisposable = values[0].observe { ... }
```

Then user types someting in textfield and changes tab, so I want to change binding to another observable

```
disposable.dispose()
obsDisposable.dispose()
textfield.text = nil
let disposable = textfield.bnd_text.bidirectionalBindTo(values[1])
```

I'm ending up with user value in values[1] like old binding is copyed to new one. Any hints/solutions? Maybe I'm doing something wrong or this is not possible?

**Comment by srdanrasic** [comment]
Hi @AdamSzeremeta ,

I'm not sure I understand what exactly you're trying to achieve, but is replacing bindings really what you need? You should probably have one Observable per Text Field and then instead of changing bindings, change values of those observables.
