### ISSUE TITLE
How to define EventProducer for multiple items from one array?

### ISSUE THREAD

**Issue by pk1** [ReactiveKit/Bond#231]
Hi,

I'm currently struggling with enabling/disabling a button in my view controller by using an EventProducer from my view model. The problem is that I need to validate all items from the array tableData and validate the name and the email attributes. 
The sendButtonEnabled definition is working fine so far if I'm directly referring to single attributes from the class TableDataContactUnknown. But how can I take all items from the array tableData into account and bind such an EventProducer to my button?

Would be great if anyone of you can point me in the right direction! Any help is really appreciated.

`
viewModel.sendButtonEnabled.bindTo(sendButton.bnd_enabled)
`

```
class TableDataContactUnknown {

    var tableData = ObservableArray([ContactUnknown]())

    let name = Observable<String?>("")

    let email = Observable<String?>("")

    var sendButtonEnabled: EventProducer<Bool> {

            let nameValid = name.map { $0!.characters.count > 0 }

            let emailValid = email.map {
                $0!.rangeOfString("[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}", options:.RegularExpressionSearch)
            }

            return nameValid.combineLatestWith(emailValid).map { name, email in
                name == true && email != nil
            }

    }    
}
```

**Comment by srdanrasic** [comment]
Closed as outdated.
