### ISSUE TITLE
How I use the framework to bind the viewModel to model

### ISSUE THREAD

**Issue by ryokinki** [ReactiveKit/Bond#233]
I have a problem when use the framework In user MVVM
this is the viewModel  and model code ------------------

import Foundation
import Bond

class QMUser: NSObject {

```
var name: String = ""

var age: Int = 0

// MARK: -
class var share: QMUser {
    struct Singleton {
        static let singleton = QMUser()
    }
    return Singleton.singleton
}
```

}

class QMUserViewModel: NSObject {

```
// MARK: -
class var share: QMUserViewModel {
    struct Singleton {
        static let singleton = QMUserViewModel(user: QMUser.share)
    }
    return Singleton.singleton
}

var user: QMUser? {
    didSet(newValue) {
        self.nick.next(newValue!.name)
        self.age.next(newValue!.age)
    }
}
var nick: Observable<String?> = Observable(nil)
var age: Observable<Int> = Observable(0)

required init(user: QMUser) {
    self.user = user
}
```
## }

becauser the user is perhaps be changed by Server Download things or change by custom to up to Server, I will only change the user model,and to promise show the user info in UI real time, bur how I use swifyBond to bond the viewModel to my user model, -----
if I have to change the user model properties to var name: Observable(String)? var age: Observable(Int)? but if I do this way ,I use the objectMapper to convert Server Json to my user model,
 that will be dificult to deal with the Server Json user objectMapper, if you have a good ideal or something I do incorrect ,please give me some guide, I just change from OC 1 months, just a new hand in swift ,thank you very much

**Comment by srdanrasic** [comment]
Closed as outdated.
