### ISSUE TITLE
How to access buffers.

### ISSUE THREAD

**Issue by dreday966** [ReactiveKit/Bond#234]
For Example ,
1. I have a let a = Observable(0).then a.next(0).the situation I want observe
2. or I have a let a = Observable(0).then a.next(1).don't want observe
And i want check if the new value equal to the previous.I find no api to implement this.How to solve this?

**Comment by yanamura3** [comment]
@dreday966 
How about create Bond extension in your project like below
```
import Bond

extension EventProducerType {
  public func same() -> EventProducer<EventType> {
    return EventProducer(replayLength: replayLength) { sink in
      var lastEvent: EventType? = nil
      return observe { event in
        if lastEvent == nil || lastEvent! == event {
          sink(event)
          lastEvent = event
        }
      }
    }
  }
}
```
