### ISSUE TITLE
NSTextField objectValue binding for NSFormatter support (Date Formatting)

### ISSUE THREAD

**Issue by lambdaupb** [ReactiveKit/Bond#236]
Hi, I'm quite new to the cocoa ecosystem so I apologise for possibly wrong assumptions.

I have a `NSTextFIeld` with an attached `NSDateFormatter` in the View and an `Observable<String>` in my Model.

I can bind the observable to the bnd_text property, but that bypasses the NSDateFormatter.

A useful addition would be a Sink only binding target for the `setObjectValue` method of NSTextField to support attached `NSFormatters`.

I looked into it, but I'm not yet familiar enough everything to implement it.

**Comment by curtisforrester** [comment]
Hi - and welcome to the ecosystem. Mind the Tigers :)

If I'm understanding, you'd like to set the text of the NSTextField to the NSDateFormatter result of the observed date (though it appears you have the date as a string?). In Swift I display a date like this:

```
self.dateStart
     .map { date in
          return MyDateFormatters.shortDateFormatter.stringFromDate(date)
     }
     .bindTo(self.dateLabel.bnd_text)

```

**Comment by lambdaupb** [comment]
Thanks for taking the time to answer.

`Observable<NSDate>` of course :) error while typing this up.

This is pretty much what I ended up doing.
```
.map({(date) -> String in  cell.textField!.formatter?.stringForObjectValue(date))!}).bindTo(cell.textField!.bnd_text)
```
(I'm not sure anymore if that worked out)

Inside a TableViewDelegate.

The thing is:

The TextField owns a DateFormatter (which might be changed in the NIB or by the system or whatever) and applies it by itself when using the `NSTextField.setObject(NSDate)` setter.

Thats why a Sink-Only binding target for `.setObject()` might be useful.
