### ISSUE TITLE
Problem with Observe

### ISSUE THREAD

**Issue by krunalsheth** [ReactiveKit/Bond#237]
many times, i need functionality where i just need to check for flag exactly once and not more. for cases, where i need to see if the flag is already set. simple code doesn't really detach binding if the flag is already set right when binding is setup.

for eg

```
flag.observe { [unowned self] value in 
  if value {
    self.doSomething()
    bindingBag.dispose()
  }
}.disposeIn(bindingBag)
```

for above code, if the value of the flag is already true, bindingBag.dispose doesn't really dispose as when the bindingBag.dispose executes inside closure, the disposableType isn't added into bindingBag.

What would be the best way to handle this issue?  i know i can write code like below but i am looking for more elegant solution. 

```
if flag {
  self.doSomething()
}
else {
  flag.observe { [unowned self] value in 
    if value {
      self.doSomething()
      bindingBag.dispose()
    }
  }.disposeIn(bindingBag)
}
```

Thanks.

**Comment by CallumOz** [comment]
I know this is an old issue but I come across it and it got me thinking.
Here is my proposition (it's untested), it would need to be added directly into [EventProducer.swift](https://github.com/SwiftBond/Bond/blob/master/Bond/Core/EventProducer.swift) since `replayBuffer` is private.

```swift
public extension EventProducer {

    public func observeOnce(observer: Event -> Void) -> DisposableType {
        if let last = replayBuffer?.last {
            observer(last)
            return SimpleDisposable()
        }
        else {
            var disposable: DisposableType!
            disposable = observeNew { (event) in
                observer(event)
                disposable?.dispose()
            }
            return disposable
        }
    }
}
```
And you would use it like this:
```swift
flag.filter { $0 }
    .observeOnce { [unowned self] (_) in
        self.doSomething()
    }
    .disposeIn(bindingBag)
```

I hope someone will found this useful someday 😄

**Comment by feighter09** [comment]
@CallumOz was very helpful to me!

**Comment by CallumOz** [comment]
I'm glad it was helpful to someone 😉
