### ISSUE TITLE
Observable count for ObservableArray

### ISSUE THREAD

**Issue by LeeroyDing** [ReactiveKit/Bond#241]
It would be very handy to have an observable count that updates itself when the `ObservableArray`'s `count` changes.

**Comment by curtisforrester** [comment]
Agree. Might be a better way, but here's what I do for now:

```
var counter: Int = 0
@IBOutlet weak var someLabel: UILabel!
// ....
self.myObservableArray.observe({ item in
    self.counter = item.sequence.count
    // Or to show in a label...
    self.someLabel.text = "\(item.sequence.count)"
})
```

When the array is changed the block will be called, updating the counter or label's text.
