### ISSUE TITLE
Cannot bind to NSButton state?

### ISSUE THREAD

**Issue by ndevenish** [ReactiveKit/Bond#247]
I've created a simple window with a checkbox NSButton and a push NSButton. I've bound it with the checkbox to `checkButton` and the push button action to doOut, with the following controller:

``` swift
class ViewController: NSViewController {
  @IBOutlet weak var checkButton: NSButton!
  var checkStatus = Observable<Int>(0)

  override func viewDidLoad() {
    super.viewDidLoad()
    checkButton.bnd_state.bindTo(checkStatus)
  }

  @IBAction func doOut(sender: AnyObject)
  {
    Swift.print("Observed: \(checkStatus.value)")
    Swift.print("Button:   \(checkButton.state)")
  }
}
```

I'd expect the `checkStatus` variable to mirror the button state. Upon running, without altering the checkbox:

```
Observed: 1
Button:   1
```

However, after unchecking the box, the output is:

```
Observed: 1
Button:   0
```

e.g. the status variable is not being updated beyond the initial bind (when it is synchronised once). 

Have I just misunderstood the binding altogether? The directions seems to be right, both because of examples and `NSTextView` instances seem to work fine. I've had similar behaviour trying to use `bnd_associatedObservableForValueForKey` to add a date binding to `NSDatePicker`, and ended up wrapping the event stream to get that to work (one-way).

**Comment by srdanrasic** [comment]
Hey @ndevenish, sorry for the late replay. macOS supported is very limited, but I in v5 it should work if you're still using it.
