### ISSUE TITLE
Using collection functions like "sizeforitematindexpath" 

### ISSUE THREAD

**Issue by mingyeow** [ReactiveKit/Bond#248]
I am using bond's method to load my collectionview. doing so means that i am not setting the viewcontroller as the datasource.

However, i need the other functions like sizeforitematindexpath. how do i access those? 

```
    profileVM!.tagsArray.lift().bindTo(tagsCV){ indexPath, dataSource, collectionView in
      let cell = collectionView.dequeueReusableCellWithReuseIdentifier("tagCell", forIndexPath: indexPath) as! TagCell
      cell.tag_object = dataSource[indexPath.section][indexPath.row]
      return cell
   }
```

**Comment by adhanji** [comment]
@mingyeow It seems like we can just use the delegate methods as normal based off this issue: #230
