### ISSUE TITLE
filter and observeNew doesn't work correctly

### ISSUE THREAD

**Issue by ohde-sg** [ReactiveKit/Bond#258]
Hi SwiftBond is powerfull and excellent but I have realized following bugs
following code doesn't work correctly

``` swift
        let age = Observable<Int>(0)

        age.filter{ (age) -> Bool in return age > 20 }
            .observeNew{ (age) in print("\(age)") }

        age.value = 21
```

print("(age)") should fired if age.value is changed to 21.
But not fired.

following code work correctly

``` swift
        let age = Observable<Int>(21)

        age.filter{ (age) -> Bool in return age > 20 }
            .observeNew{ (age) in print("\(age)") }

        age.value = 21
```

Result is printed "21"

Difference two codes is Observable<Int>(0) => Observable<Int>(21).
I think that observe couldn't count up if value doesn't meet filter.
so observe is not work correctly if you use observeNew.

**Comment by yanamura3** [comment]
@ohde-sg 
This behavior is not bug.
"observeNew" is same meaning of "skip(1).observe".

I think what you want to do is below.
```
age.skip(1)
    .filter{ (age) -> Bool in return age > 20 }
    .observe{ (age) in print("\(age)") }
```
