### ISSUE TITLE
UITableView edit actions without UITableViewDataSource

### ISSUE THREAD

**Issue by zach-cmiel** [ReactiveKit/Bond#259]
With a UITableView in Bond since there is no need to set the UITableViewDataSource since Bond takes care of that, there is no way for the UITableViewCell to have edit actions since the methods to add them are in the data source delegate. Is there a way to add them to a UITableView in Bond?

**Comment by srdanrasic** [comment]
Hi @zach-cmiel, you can use proxy data source. Check out bindTo method: https://github.com/SwiftBond/Bond/blob/master/Bond/Extensions/iOS/UITableView%2BBond.swift#L204

**Comment by curtisforrester** [comment]
For my UITableViewController that is its own data provider, my first "bindTo" line reads:

```
self.bindDisposable = self.myArray.lift().bindTo(self.tableView, proxyDataSource: self) { indexPath, dataSource, tableView in
...
}
```

**Comment by zach-cmiel** [comment]
So @curtisforrester what is self.bindDisposable's type in this situation?

**Comment by pk1** [comment]
@zach-cmiel 
can you please provide more information on how to exactly use edit actions with a proxy data source?
BNDTableViewProxyDataSource seems not to implement the editActionsForRowAtIndexPath function.

**Comment by srdanrasic** [comment]
@pk1 that's possible with reactive delegates explained in the readme of new Bond v5.
