### ISSUE TITLE
Crash when appending to collection bound to UICollectionView

### ISSUE THREAD

**Issue by AnthonyMDev** [ReactiveKit/Bond#282]
When appending or removing an item from a `MutableObservableArray` that is bound to a collection view I get a crash.

`'NSInternalInconsistencyException', reason: 'attempt to insert section 1 but there are only 1 sections after the update'`

It seems as if an item should have been inserted, but instead, a new section was inserted. 

When deleting I get this error:

`'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (0 inserted, 1 deleted).'`

**Comment by AnthonyMDev** [comment]
It looks like you are using an `IndexPath` with only one index in your `events`. `collectionView.insertItems(at: indexPaths)` assumes this one index is the section.

**Comment by AnthonyMDev** [comment]
So, I was able to fix this by changing `kind` on `ObservableArray` to return `IndexPath`s with a row and section.

```` swift
  public var kind: DataSourceEventKind {
    switch change {
    case .initial:
      return .reload
    case .inserts(let indices):
        return .insertRows(indices.map({ IndexPath(row: $0, section: 0) }))
    case .deletes(let indices):
      return .deleteRows(indices.map({ IndexPath(row: $0, section: 0) }))
    case .updates(let indices):
      return .reloadRows(indices.map({ IndexPath(row: $0, section: 0) }))
    case .move(let from, let to):
        return .moveRow(IndexPath(row: from, section: 0), IndexPath(row: to, section: 0))
    case .beginBatchEditing:
      return .beginUpdates
    case .endBatchEditing:
      return .endUpdates
    }
  }
````

I'm not sure if this breaks anything else, but it does fix this issue.

Hopefully we can get a fix for this sent out ASAP?

Thanks!

**Comment by srdanrasic** [comment]
Hi @AnthonyMDev, yeah, that was ugly thing. I had it fixed yesterday but could not release due to issues on CocoaPods servers. I retried now and it seems it worked. Please try beta6.

**Comment by EEimer** [comment]
Hi @AnthonyMDev, hey @srdanrasic, 

Had the same problem with beta 4, just updated to beta 6.

Issue is fixed => Thanks  :)

**Comment by AnthonyMDev** [comment]
Thanks! It works perfectly.
