### ISSUE TITLE
Feature Request - Property from RKKeyValueSignal

### ISSUE THREAD

**Issue by AnthonyMDev** [ReactiveKit/Bond#288]
I find myself constantly needing a `Property` from a key value signal. I'm forced to create the property with a made up value, then bind it to the signal.

````swift
let name = Property<String?>(nil)
object.valueFor(keyPath: "name").bind(to: name)
````

I feel like this is common enough boilerplate code that we should make it simpler.

Either

````swift
let name: Property<String?> = object.valueFor(keyPath: "name").toProperty()
````

or

````swift
let name: Property<String?> = Property(object.valueFor(keyPath: "name"))
````

Thoughts?

**Comment by srdanrasic** [comment]
Why exactly do you need a Property and why is Signal not enough?

**Comment by AnthonyMDev** [comment]
Because I'm using them on a view model object. After editing the view model object, I need to be able to retrieve the values and use them to generate JSON for uploading objects to my REST API.
I MAY be able to refactor that code to use `Signal`, but it would be awkward and would likely result in more weird boilerplate code.

The reason for this proposal is that I believe this would make the public API for the `Property` type more easily consumable. If the argument against it is, "Well why would you need a `Property` instead of a `Signal`?" then why do we even include the `Property` object in the library in the first place? Obviously there are situations where a `Property` is more convenient, or even necessary, so I don't see why we wouldn't want to make it as easy to use as `Signal`.

I recognize and respect the desire to keep this library as lightweight as possible. However, from my team's personal experience, this is such a commonly used practice, that I feel it is worth including.

**Comment by srdanrasic** [comment]
I was trying to see bigger picture, that was not my argument. Also, argument about keeping things lightweight applies only to ReactiveKit. I'm fine with Bond growing.

There are two problems with Property for KVO.

1. Lifecycle management. Property is an object that can be observed while it's alive. When it's deallocated it will signal completed event and terminate. If I just wanted to observe KVO stream or transform it using FRP paradigm I would have to store/retain the property somewhere just to keep it alive.

2. It duplicates value. In your example, name would be retained by the original object and by the property. I'm aware it's just one additional pointer, but it's not clean approach. It's like a cache so it has a potential to cause issues.

However, I see that there is a room for improvement around KVO. Let me think for a day about this, I might have some ideas to make your use case better.

**Comment by AnthonyMDev** [comment]
Understood.

Comments on your problems:

1. I think that's just fine though. The property WOULD be retained as long as you want to access it. This doesn't seem to add any complexity to me.

2. Sure, it does duplicate values. The issue here is that a property is being used when you want to be able to observe changes to the KVO but also want to be able to *set* the value. If I just want to observe the KVO, then the `Signal` is fine. If I want to be able to set the value from my view model also, then I need a `Property`. Using proper dependency inversion, my controllers don't know about my actual model object, just the view model via a protocol. To set the value on the observed object I currently am doing this:

````swift
let name = Property<String?>(nil)
object.valueFor(keyPath: "name").bind(to: name)
name.observeNext { object.name = $0 }.disposeIn(bnd_bag)
````

Being able to create a `Property` from an `RKKeyValueSignal` would include the ability to *set* the value on the `Property` and bind to the KVO bi-directionally.

Thanks for your time as always @srdanrasic

**Comment by srdanrasic** [comment]
@AnthonyMDev hope a way to make property from dynamic subject as described in #290 will do?

**Comment by AnthonyMDev** [comment]
I'm going to look into this either today or tomorrow and I'll let you know my comments. From the description in #290, it sounds like it will work wonderfully.

**Comment by AnthonyMDev** [comment]
@srdanrasic This does a huge part of what I need. After starting to implement it, I realized that I also need the ability to transform the value from the `RKKeyValueSignal` to a different type. (ie. `String` to `Int`). I've created PR #306 to add this functionality. I hope that this PR works for you. Thanks!
