### ISSUE TITLE
Call stack limit reached

### ISSUE THREAD

**Issue by chrisjb82** [ReactiveKit/Bond#302]
I have ported a project from Swift 2.3 to Swift 3 and along with it Bond from 4.3.1 to 5.0.0-beta8.
All the code compiles and runs, however, i'm noticing an issue with code which used to work using Bond 4.3.1.

There is a UITableViewController which is bound to a ViewModel. In the TableView there are cells which when tapped insert a new cell which is a date picker. 
Each of the TableViewCells have an Observable which holds the cells 'valid' state (based on the text entered). All of these 'valid' state are tracked and each time any changes a global 'valid' state it updated. This is used to drive a save/cancel button on the page through bonds.
When I click on the TableViewCell to expand/collapse the date picker all works fine to being with, however, after a few tries the whole UI locks up. 

Using instruments i can see that the reason why is 'Call stack limit reached', the next item in the call stack is 'ReplaySubject.(on(Event<A, B>) -> ()).(closure #1).(closure #1)' and then a few steps lower is 'SignalProtocol.(filterRecursiveEvents() -> Signal<A.Element, A.Error>).(closure #1).(closure #1)'. Both items are from ReactiveKit.

It would appear that 'filterRecursiveEvents()' is probably the culprit but i don't really know.

Has anyone else experienced issues like these?

**Comment by srdanrasic** [comment]
'filterRecursiveEvents' was removed and replaced with something else few weeks ago. Would you mind trying the latest version?

If it still persists, there must be something in your code that triggers infinite cycle. If you could trace it it would be great.

**Comment by chrisjb82** [comment]
I'll have a look this weekend and get back to you, hopefully it'll work now with the current stable release.

**Comment by chrisjb82** [comment]
Hi @srdanrasic, i tried the code again after updating to Bond v5.0.2 and it would appear the issue is no longer present.

Do you know what could've been causing the issue in the first place? It would be good to know just incase i've done something i shouldn't have when hooking up the bindings on my TableView.

Many thanks again for a great Framework. Bond should be included as standard in iOS IMO!

**Comment by srdanrasic** [comment]
Glad to hear that :) Thanks!

I'm not sure. There must had been an implicit cycle where A was updating B and B was updating A. Final release of v5 improved support for such cycles. Hopefully that's what fixed it.
