### ISSUE TITLE
UIBarButtonItem.bnd_tap can have only 1 observer.

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/Bond#303]
I made a simple bug demo. https://github.com/jechol/bond-bar-button-item-bug-case
Only last observer receives event from `bnd_tap`.

While `UIControl` can have multiple targets by `addTarget`,
UIBarButtonItem, which not inherits from UIControl, can only have one target by `button.target = object`.

Error is caused in `BNDBarButtonItemTarget` at
https://github.com/ReactiveKit/Bond/blob/d0ff7fdf2fa98f8f262a356587537eec18d9f3ed/Sources/UIKit/UIBarButtonItem.swift#L58

@srdanrasic  Could you please check this out?

**Comment by srdanrasic** [comment]
Thanks @jechol, I'll take a look during the weekend.

**Comment by srdanrasic** [comment]
Yeah, this need to be improved. Unfortunately it's not that trivial :)

**Comment by jechol** [comment]
Yeah, I tried to patch myself, but target is weak ref so that released immediately.

I'm working around by call `bnd_tap` only once in client side now.

**Comment by rsaarloos** [comment]
As far as I know this behaviour was not like this in the `rTap` of ReactiveUIKit. In my project I replaced ReactiveUIKit with Bond and I'm running in the same behaviour. I did not really understand what was going on as only my latest `bind` did actually work. But this explains the behaviour at least. Maybe this info will help @srdanrasic ?

**Comment by srdanrasic** [comment]
Thanks everyone. Support for multiple observers is implemented in v5.1..
