### ISSUE TITLE
Throttle

### ISSUE THREAD

**Issue by elementsrtyte** [ReactiveKit/Bond#304]
```
class LocationViewModel {
    let searchText = Observable<String?>("")

    init(){
        let _ = searchText.throttle(seconds: 2).observeNext {
            print($0) //This is the issue line right here.
        }
    }
}


class ViewController: UIViewController {
    let viewModel = LocationViewModel()
    @IBOutlet weak var searchTextfield: UITextField!

    override func viewDidLoad() {
        super.viewDidLoad()
        self.viewModel.searchText.bidirectionalBind(to: self.searchTextfield.bnd_text)
    }
}
```

When I try to throttle the searchText, I get the first letter that goes thru rather than the last.  For example...
If I write the word 'search' in <2 seconds, The console will print out just 's', but I believe that I should be getting an 'h'.

Has anyone else experienced issues like these?

**Comment by srdanrasic** [comment]
This could be a bug... I'm investigating.

**Comment by elementsrtyte** [comment]
Any updates on this one @srdanrasic ?

**Comment by srdanrasic** [comment]
Hi @elementsrtyte, it was fixed last week. Sorry I forgot to notify you. Thanks for reporting this!
