### ISSUE TITLE
Observing on textfield text changes different in 5.0

### ISSUE THREAD

**Issue by SCasarotto** [ReactiveKit/Bond#312]
I want to preface this with the fact that I am not sure if this come from lack of knowledge or a bug in 5.0.

Pre swift 3, I had a custom textField class that handled some validation and I bound the text value so that each time the value changed the validation script fired:

```
//Bind Validation
self.textField.bnd_text
.observe{[unowned self] _ in self.validateTextField() }
.disposeIn(bnd_bag)
```

Upon upgrading to swift 3 and Bond 5.0 I have:

```
//Bind Validation
self.textField.bnd_text
.observeNext{[unowned self] _ in self.validateTextField() }
.disposeIn(bnd_bag)
```

However it seems that they function differently. I currently set the value of my text based on values in my model. In Swift 2.3 this would trigger the `self.validateTextField()` but now in Swift 3 (bond 5.0) the only way to trigger `self.validateTextField()` is by actually tapping into the textfield. Updating the textfield.text value doesn't seem to be caught by the observeNext.

Has there been a change in functionality or is this simply a lack of knowledge on my part? Any help would be greatly appreciated. Thanks!

**Comment by srdanrasic** [comment]
Hmm, I don't think that setting `textfield.text` ever fired an event, but setting `textField.bnd_text.value` did. It's not possible to do that any more, although you could simulate it with a dummy binding:

```swift
Signal<String, NoError>.just("new value").bind(to: textField.bnd_text)
```

Make sure you `import ReactiveKit` (a Bond dependency). 

You can even write it as an extension on DynamicSubject:

```swift
extension DynamicSubject2 {

  func set(value: Element) {
    Signal<Element, NoError>.just(value).bind(to: self)
  }
}

textField.bnd_text.set(value: "new value")
```

If you think that this is something that is widely used and should be part of the framework, let's add it as a todo for next version.

**Comment by SCasarotto** [comment]
Ah yes sorry to be more clear. I was updating the `bnd_text` value with the following before and currently.

`Driver.sharedInstance.nameF.bind(to: fNameInput.textField.bnd_text)`

In Bond 4 this was triggering my `validateTextField()` but now is not.

**Comment by SCasarotto** [comment]
This work-around seems to have the intended affect. 
		
```
Driver.sharedInstance.nameF.bind(to: fNameInput.textField.bnd_text)
Driver.sharedInstance.nameF.observeNext
	{[unowned self] text in
		quickPrint("Observe Next Attempt")
		self. fNameInput.validateTextField()
	}
	.disposeIn(bnd_bag)
```

However it feels like it should work the way I described before and did work in previous version.

Thoughts @srdanrasic ?

**Comment by srdanrasic** [comment]
Planning to make value settable again.

**Comment by srdanrasic** [comment]
Implemented as explained here: https://github.com/ReactiveKit/Bond/issues/291#issuecomment-260435006.
