### ISSUE TITLE
ReactiveKit Removed "associatedtype Error: Swift.Error" from Bindable

### ISSUE THREAD

**Issue by SCasarotto** [ReactiveKit/Bond#313]
ReactiveKit removed `associatedtype Error: Swift.Error` in https://github.com/ReactiveKit/ReactiveKit/commit/49e1b839cfdbd508e3ef5016c3fb0357d3f00627. This stops bond from building because NSObject.swift. Specifically the following:

 ```
 /// Bind `signal` to `bindable` and dispose in `bnd_bag` of receiver.
  @discardableResult
  public func bind<O: SignalProtocol, B: BindableProtocol>(_ signal: O, to bindable: B) where O.Element == B.Element, O.Error == B.Error {
    signal.bind(to: bindable).disposeIn(bnd_bag)
  }
  
  /// Bind `signal` to `bindable` and dispose in `bnd_bag` of receiver.
  @discardableResult
  public func bind<O: SignalProtocol, B: BindableProtocol>(_ signal: O, to bindable: B) where B.Element: OptionalProtocol, O.Element == B.Element.Wrapped, O.Error == B.Error {
    signal.bind(to: bindable).disposeIn(bnd_bag)
  }

```

**Comment by srdanrasic** [comment]
Oh, Carthage is picking up latest version I guess... I'll be releasing update to Bond today that fixes this.

**Comment by SCasarotto** [comment]
Great thanks. 

Also I noticed the readme says cocoaPod integration `pod 'Bond', '~> 5.0'` however I attempted to use that last night with no luck. It seemed like I still had to use `pod 'Bond', '~> 5.0.0-beta10'`.

**Comment by srdanrasic** [comment]
Ok, I've pushed latests version. We're out of beta now!
