### ISSUE TITLE
Map one observable array to another

### ISSUE THREAD

**Issue by AlexEdunov** [ReactiveKit/Bond#315]
I still use Bond 4. Could you provide an example of mapping one observable array to another? Syntax is not clear for me.

For example I have a class for Deal:

    class Deal {
        var startDate: NSDate
        var endDate: NSDate
    }

And want to map and then bind Deal observable array to NSTimeInterval observable array:

    private var bnd_dealArray = ObservableArray<Deal>()
    private var bnd_dealDurationArray = ObservableArray<NSTimeInterval>()

    bnd_dealArray
        .map { (deal) -> NSTimeInterval in
            return deal.startQuoteDate.timeIntervalSinceDate(deal.endQuoteDate)
        }
        .bindTo(bnd_dealDurationArray)

I'd like to fix this function.

**Comment by CallumOz** [comment]
You need to use `ObservableArray.appleOperation(_:)`.
Well anyway that's how I dealt with it.

```swift
bnd_dealArray
    .map { (deal) -> NSTimeInterval in
        return deal.startQuoteDate.timeIntervalSinceDate(deal.endQuoteDate)
    }
    .observe { (event) in
        bnd_dealDurationArray.applyOperation(event.operation)
    }
```

Hope that helps 😉

**Comment by AlexEdunov** [comment]
Thanks a lot!
