### ISSUE TITLE
Unable to get bidirectionalBind actually work

### ISSUE THREAD

**Issue by cowgp** [ReactiveKit/Bond#316]
the super quick mention of bidirectionalBind in the readme seems to imply that if you had a property, perhaps a String, on an object that you could two-way bind with a text field
```swift
viewModel.username
  .bidirectionalBind(to: usernameTextField.bnd_text)
```

So in trying to implement this, I have an object like

```swift
class WLEmail: Object, Mappable {
    dynamic var id: String? = nil
    dynamic var address: String? = nil
    ...
```

and then I tried to two-way bind the address with a text field - rather similar to the hypothetical example.
```swift
email.address.bidirectionalBind(to: customView.emailField.bnd_text)
```

this results in an compile error
> Value of type 'String?' has no member 'bidirectionalBind'

I tried swapping out to a Signal rather than a string, but that didn't work and the optionality of the string has no bearing either.  Any pointers on how to make this actually work?  there don't seem to be any examples in then playground or anything.

**Comment by srdanrasic** [comment]
Hi @cowgp,

The trick is to use observable properties:

```swift
class WLEmail: Object, Mappable {
    let id: Observable<String?> = Observable(nil)
    let address: Observable<String?> = Observable(nil)
    ...
```

Without that, it's impossible to do bindings.

**Comment by cowgp** [comment]
Nice! I new there had to be a trick!  thanks for pointing me in the right direction.

**Comment by markst** [comment]
Can I confirm `bidirectionalBind` is still not possible without the use of `Observable` properties?

Since I'm using `NSManagedObject` subclass, I'm unable to setup a two way bind.

**Comment by Yasith-Thathsara-Senarathne** [comment]
> Hi @cowgp,
> 
> The trick is to use observable properties:
> 
> ```swift
> class WLEmail: Object, Mappable {
>     let id: Observable<String?> = Observable(nil)
>     let address: Observable<String?> = Observable(nil)
>     ...
> ```
> 
> Without that, it's impossible to do bindings.

This is absolutely correct
