### ISSUE TITLE
Unable to use MutableObservableArray

### ISSUE THREAD

**Issue by zdenektopic** [ReactiveKit/Bond#317]
Always builds with error: Segmentation fault 11

```
    typealias PanelType = Panel
    typealias PanelArray = MutableObservableArray<PanelType>
    
    private let _panels: PanelArray = PanelArray()
    var panels: ObservableArray<PanelType> {
        return _panels
    }
```

If I change to simple `Array`, it works just fine. `Panel` is `NSObject` subclass.

**Comment by CallumOz** [comment]
I have the same problem. I found that you need to explicitly initialise the `MutableObservableArray` with an empty array.

```swift
    private let _panels: PanelArray = PanelArray([])
```

I hope that fixes your problem too 😉

**Comment by zdenektopic** [comment]
Thanks, helped!

**Comment by Bubcho** [comment]
Thanks @CallumOz, you ended my day-and-a-half misery

**Comment by CallumOz** [comment]
@Bubcho, glad to hear that!

**Comment by Calagahn** [comment]
You saved my week and the migration of my project from Swift 2.2 to 3.0! Thanks!
For posterity, I was struggling with the following build error in two different classes :
```
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
```
Initializing the `MutableObservableArray` I was using in those classes was the key...

**Comment by yuvalt** [comment]
Thank you!

**Comment by smeis** [comment]
@CallumOz Thank you so much!

**Comment by santiagoprieto** [comment]
OMG. Savior of life.

**Comment by cartermike** [comment]
+1 good to know!
