### ISSUE TITLE
Why were map and filter removed from MutableObservableArray ?

### ISSUE THREAD

**Issue by CallumOz** [ReactiveKit/Bond#318]
In v4 I use `map` and `filter` (mainly map) to convert `ObservableArray`'s of one type to an `ObservableArray` of another type while still keeping the automatic updates.
Why were they removed?

After looking at the source code, I don't see why map can't be re-added ?
Filter even though possibly a lot more annoying to implement could also be added.

Were they removed because of lack of time to re-implement them in v5 ? In which case, would it be okay to provide a PR reimplementing them ?

**Comment by srdanrasic** [comment]
Filtering is a very complex feature to maintain. But let's keep this ticket in mind as possible enhancement.

**Comment by CallumOz** [comment]
What about map though ? It doesn't seem as complicated to me.

**Comment by srdanrasic** [comment]
Map would be simpler.Let's discuss it for next version.

**Comment by srdanrasic** [comment]
These are back sing v5.2.0

**Comment by CallumOz** [comment]
Great news, thanks 🎉
