### ISSUE TITLE
(Question) Tableview reload animation

### ISSUE THREAD

**Issue by robertodias180** [ReactiveKit/Bond#321]
is there a way to change the reload animation with bond? 

i found this #257, but I could not found the this datasource.

**Comment by Broich** [comment]
I believe you can do this with `collectionView.bnd_dataSource.forwardTo` or `tableView.bnd_dataSource.forwardTo` and assign your own data source.

**Comment by srdanrasic** [comment]
Unfortunately no. You can only disable animations.
