### ISSUE TITLE
Include of non-modular header inside framework module Bond.Bond

### ISSUE THREAD

**Issue by pk1** [ReactiveKit/Bond#322]
Hi,

I had a running project configuration using Xcode 8 and Swift 2.3. Yesterday evening I tried to migrate finally everything to Swift 3. Since then I'm facing the problem **Include of non-modular header inside framework module Bond.Bond** while trying to build my project. 

I already tried to clean several times the derived data including cleaning up the whole project in Xcode without any luck. The build setting **Allow non-modular includes in Framework modules** seems also not to do the trick.

Had anyone else of you this kind of problem and knows what the solution might be? Any information or tip is really appreciated!

**Comment by srdanrasic** [comment]
Hi @pk1,

Are you maybe using CocoaPods? If yes, do you have latest version?

**Comment by pk1** [comment]
After updating CocoaPods to version 1.1.1 and running **pod install** it started to re-create CocoaPods and this finally did the trick. Bond is now compiling without any error.

Thanks @srdanrasic and keep up the good work!
