### ISSUE TITLE
Access .array of MutableObservableArray

### ISSUE THREAD

**Issue by Joebayld** [ReactiveKit/Bond#323]
I've been using Bond4 quite heavily in my projects. But in Bond5 you made the array variable of ObservableArray FilePrivate and not accessible. This made Bond no longer usable for me... I need to be able to access the root array (or even a copy of it) for many purposes. One main reason being to serialize the array to NSCoding when saving a document. Will it be possible to make it public? Or some sort of public getter that is safe? I would like to continue to use Bond but cannot if this feature is broken. Thanks

**Comment by Joebayld** [comment]
Yeah that would be great. Or maybe a public getter only? private(set) public var array. 

I know you can use the collection methods, but I feel it would still be useful to access the underlying array in an ObservableArray. Also, would the getter need to be contained in an atomic lock?

**Comment by srdanrasic** [comment]
Implemented in v5.1.
