### ISSUE TITLE
Waiting for events and bind them to observable array

### ISSUE THREAD

**Issue by AlexEdunov** [ReactiveKit/Bond#326]
I'm receiving events from EventProducer. I'd like to collect it and if they aren't receiving (for some time), throw them all to Observable array.

As I understand it should be composition of following operators:

    eventProducer
        .throttle(time)
        .flatMap
        .bindTo

Pretty easy to understand but could not find any working example. Could you provide it?

**Comment by srdanrasic** [comment]
There is a debounce operator in Bond 5 / ReactiveKit that provides such behavior. Unfortunately it's not available in previous versions.
