### ISSUE TITLE
Can a view model's property be bidirectionally bound without instantiating an Observable?

### ISSUE THREAD

**Issue by jordancamara** [ReactiveKit/Bond#327]
So, when setting up bidirectional binding with a view model, I have to instantiated the property with an Observable. Is there an alternative way to doing this? I understand that there is a trade off and I will need to translate onto a request to be sent up through an API, but I was just wondering if there were a better way.

**Comment by srdanrasic** [comment]
Nop, Swift is not there yet. You could use KVO, but that's not a better way.
