### ISSUE TITLE
Autocorrection event missed in UITextField

### ISSUE THREAD

**Issue by chrisjb82** [ReactiveKit/Bond#328]
When a UITextField is bound to an Observable<String> changes to the text fields value may not get updated on the Observable.

Steps to reproduce:
1) add a UITextField to a view and set textField.autocorrectionType = UITextAutocorrectionType.yes
2) create a bidirectional bond between a UITextField and Observable<String>
3) add an observe event to the Observable and within it print out the value
4) type text into the text field, the value should start outputting to the console
5) input a sentence but as the last word type a name then press 'return'
6) the name will be autocorrect to have an uppercase first letter but the observation will not fire and the updated value will not be printed to the console.

i believe this is caused because the only event being listened to is UITextFieldTextDidChange, this event is not fired in the above scenario. UITextFieldTextDidEndEditing is fired and when adding this to the event list the bound value is updated and the correct value outputted to the console.

**Comment by srdanrasic** [comment]
What version of Bond are you using? I think in v5 we are observing all editing events.

**Comment by chrisjb82** [comment]
Hi srdanrasic, i'm using v4.3.1 of Bond as i was experiencing issues (#302) with v5.0.0, however, this issue appears to be apparent in v5.0.0 too.

In the file UITextField.swift bnd_attributed only monitors .editingChanged wheras bnd_txt monitors .allEditingEvents as you said, should they not be the same?

The same issue is present in UITextView.swift where only UITextViewTextDidChange is monitored.

Took me a wee while to figure out what was going on there! :)

**Comment by srdanrasic** [comment]
Yep, they should be consistent. I'll have it fixed.

**Comment by srdanrasic** [comment]
Fixed in v5.0.4.
