### ISSUE TITLE
Can't install pod 'Bond', '~> 5.1', Xcode 8.1

### ISSUE THREAD

**Issue by enigma2006x** [ReactiveKit/Bond#332]
Hello!,

I was trying to install   pod 'Bond', '~> 5.1', but I received the next message:

[!] Unable to satisfy the following requirements:

- `Bond (~> 5.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Bond (~> 5.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

best regards.

Antonio

**Comment by srdanrasic** [comment]
Did you run `pod repo update`?

**Comment by enigma2006x** [comment]
The problem was in the CocoaPods master repo, I removed the master repo and clone again and now is working, thank you.
