### ISSUE TITLE
How I can get event of pressing Return button at keyboard for UITextField?

### ISSUE THREAD

**Issue by RomanVolkov** [ReactiveKit/Bond#333]
I see all possible touch events of visual components. But, is there possibility to subscribe not on uitextfield text changed, but on pressing return button from keyboard? # #

**Comment by jordancamara** [comment]
Yes, it's possible. There is a bnd_controlEvents property on UITextField that you can subscribe to different specific events. Here is some sample code

`_ = yourTextField.bnd_controlEvents(.primaryActionTriggered).observeNext {
                self.view.endEditing(true)
                // necessary code here.
            }`

**Comment by RomanVolkov** [comment]
Great, thanks a lot
