### ISSUE TITLE
Bind TO MutableObservableArray

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/Bond#335]
In ReactiveKit 2, it was possible to bind a stream of mutations (`Stream<CollectionChangeset<[ItemType]>>`) to a collection property (`CollectionProperty<[ItemType]>`), which I found super useful - in Bond 5, I can't find an analog to this with `MutableObservableArray`. The `subject` is fileprivate, i.e. totally inaccessible (I think). 

This is quite a shame for me - is there any other way to achieve this (perhaps I've missed something)?  Any tips appreciated :) thanks!

**Comment by iandundas** [comment]
(basically I used to pipe `CollectionChangeset` events through to be applied on to the collection, but the new `ObservableArrayChange` struct doesn't carry the collection as well so I guess it's impossible? :( )

**Comment by srdanrasic** [comment]
It would be possible to implement that, basically we would need to expose underlying subject and do minor adjustments. The `ObservableArrayEvent` still carries source array.

The reason this is not implemented is that such feature can put destination array into invalid state. You could be piping two collections into one and whoever is observing that one would probably see a mess.

Perhaps you could reorganise your code to work with the same instance of the array?

**Comment by iandundas** [comment]
Actually it was more ambitious than that - I'd built a lib (utilising `CollectionProperty`) to swap out different reactive collection providers on the fly (I have adapters for Realm's `Result`, `NSFetchedResultsController` and static arrays for now but it should be pluggable enough to work with anything that emits changesets), with CollectionProperty diffing the two collections and my lib then rebinding to the new provider. 

Library: [https://github.com/iandundas/HotTakeCore](https://github.com/iandundas/HotTakeCore)
Demo: [https://github.com/iandundas/HotTakeDemo](https://github.com/iandundas/HotTakeDemo)

I understand the valid concerns about getting into invalid state using it as you described above, but for this particular usage it was working well (tests etc) and I've used it in a shipping app. 

I'm wondering where to go next r.e. adopting Swift 3 and upgrading to ReactiveKit 3 + Bond. I could port the existing `CollectionProperty` from ReactiveKit 2 to use 3.0 and get it to compile for Swift 3, but I think this could be a lot of work, and depends on the magnitude of the changes between 2.1 and 3.0 🙂 (which I've not checked fully yet)

The better alternative would be, as you suggested above, somehow surfacing the subject within Bond and going from there - do you think that could potentially be okay? 

> The ObservableArrayEvent still carries source array (i.e. a reference to it)

ah yeah! I had another look (it was midnight last night😛) - I'd thought there was only ObservableArrayChange, but yes ObservableArrayEvent is indeed perfect.

Cheers 🙇🏻

**Comment by srdanrasic** [comment]
Since you've put so much effort into that, let's work this issue out :)

I'll need few days to find the best solution or at least make binding available again.

**Comment by iandundas** [comment]
Thanks a lot! Appreciate it.
Going camping now, back in a couple ⛺️

**Comment by srdanrasic** [comment]
Implemented :) Also added map and filter operators for observable arrays.

**Comment by iandundas** [comment]
Awesome!! Many thanks :) I'll check it out today

**Comment by iandundas** [comment]
Apologies, you fixed it quickly but I haven't integrated it yet - will definitely do it tomorrow. Life has got in the way 🗓 cheers

**Comment by srdanrasic** [comment]
No worries :)
