### ISSUE TITLE
How can I use UITableViewDataSource methods with SwiftBond?

### ISSUE THREAD

**Issue by Bubcho** [ReactiveKit/Bond#336]
Hello all,

I have a `UITableView` that's bound to a `MutableObservableArray` using the `bind(to:animated:createCell:)` method. Now I need to enable the swipe to delete feature of the table view, so e.g. I have to implement `tableView(_:commit:forRowAt:)` from `UITableViewDataSource`. I've played around with the `TableViewBond` protocol, but couldn't figure it out, and I thought I'd ask.

**Comment by srdanrasic** [comment]
You can use `tableView.bnd_dataSource.forwardTo = self` to forward calls to your own object where you should implement `tableView(_:commit:forRowAt:)`.

To quote the Readme:
> Note: Protocol proxy takes up delegate slot of the object so if you also need to implement delegate methods manually, don't set tableView.delegate = x, rather set tableView.bnd_delegate.forwardTo = x

**Comment by Bubcho** [comment]
Hello @srdanrasic,
Thank you for your reply. I tried forwarding the data source back to my view controller, but then my view controller needs to conform to UITableViewDataSource and implement `tableView(_:numberOfRowsInSection)` and `tableView(_:cellForRowAt)`. These two methods are already handled by Bond, so how do I proceed in this case?

**Comment by srdanrasic** [comment]
Yeah, that's one drawback of it. You can either not conform to the delegate protocol (but still implement the method), or you could just provide dummy implementation since those methods will never actually be called.

**Comment by Bubcho** [comment]
@srdanrasic, the strange thing is that I'm experiencing the opposite behavior - when I implement the method `tableView(_:commit:forRowAt:)` without conforming to the data source protocol, the method never gets called and I don't have swipe-to-delete. If I conform to the protocol and provide dummy implementations to the required methods, those methods actually get called and things mess up (I get a `NSInternalInconsistencyException` because the dummy `tableView(_:numberOfRowsInSection:)` method returns 0 and I'm adding to the observable dictionary).

Don't know If it's related, but I also forward the table view's delegate in this way to have a custom section header. And in the case of the delegate, it works by only providing the method implementation `tableView(_:viewForHeaderInSection:)`, regardless of whether I conform to `UITableViewDelegate` or not.

**Comment by srdanrasic** [comment]
Ah :/ When you don't conform to protocol you have to use ObjC name `tableView(_:commitEditingStyle:forRowAtIndexPath:)`. It's something in ObjC-Swift that messes up otherwise...

**Comment by Bubcho** [comment]
@srdanrasic, indeed, you're right! I have spent a lot of time on this, but I haven't thought about using the ObjC name of the method. Thank you for your support and I also have to congratulate you on your beautiful and extremely useful framework. Have a great weekend! :-)
