### ISSUE TITLE
How to downcast the return type of an ObservableArray<T>?

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveKit/Bond#337]
I'm using the new `filter(…)` methods on `ObservableArray<T>` that were introduced in v5.2.0 (thanks!), however I'm having trouble filtering based on a descendent type of `T` (let's call it `U`) and then returning the `ObservableArray<U>`. 

Normally I'd use a `flatMap(…)` for this with a signal, however `map` and `flatMap` are both returning the underlying array.

Essentially my use case is that I'd like to observe changes to a "root" `ObservableArray`, but through the lens of a specific type. Not sure of the technical feasibility of this, to be honest.

**Comment by srdanrasic** [comment]
Is following not working

```
array.filter { $0 is U }.map { $0 as! U }
```

?

**Comment by tonyarnold** [comment]
I don't think I explained this very well. 

I basically wanted a "child" `ObservableArray` that was a filtered/mapped derivative of a parent `ObservableArray`. 

I basically have something like this now:

```swift
typealias Filter = (DocumentItem) -> Bool

var filter = Observable<Filter?>(.none)

var children: ObservableArray<DocumentItem> {
    return self.mutableChildren as ObservableArray<DocumentItem>
}

var filteredChildren: ObservableArray<DocumentLayer> {
    return self.mutableFilteredChildren as ObservableArray<DocumentLayer>
}

private let mutableChildren = MutableObservableArray<DocumentItem>([])
private let mutableFilteredChildren = MutableObservableArray<DocumentLayer>([])

func observeChangesToFilteredChildren() -> Signal<[DocumentItem], NoError> {
    return combineLatest(self.children, self.filter) { event, filter in
        guard let filter = filter else {
            return event.source.array
        }

        return event.source.array.filter(filter)
    }
}

self.observeChangesToFilteredChildren()
    .flatMap { $0 as? DocumentLayer }
    .ignoreNil()
    .collect()
    .observeNext { [unowned self] children in
        self.mutableFilteredChildren.replace(with: children, performDiff: true)
    }
    .disposeIn(self.disposeBag)
```

This allows me to attach a table view or data source to the `filteredChildren` `ObservableArray` and receive appropriate diffs/updates. It feels a bit heavy, but I'm yet to see any performance issues with it (this is in a desktop app, so memory is a bit less of a concern).

**Comment by srdanrasic** [comment]
Since your filter is observable, filtered array is just "a derivative of the filter". So I think the simplest solution here is to flatMap filter into filtered array.

```swift
filter.flatMapLatest { (filter) -> Signal<ObservableArrayEvent<DocumentLayer>, NoError> in
  if let filter = filter {
    return children.filter(filter).map { $0 as! DocumentLayer }
  } else {
    return ObservableArray<DocumentLayer>([]).toSignal()
  }
}.bind(to: mutableFilteredChildren)
```

It would be much nicer if the filter was not optional :)

**Comment by tonyarnold** [comment]
Could definitely do that, but I think you've well and truly answered my question. Thank you!

**Comment by tonyarnold** [comment]
Is there a way to have the flatMapLatest return an `ObservableArray<DocumentLayer>` directly, or do I absolutely need to bind to the mutable instance to do that? It'd be nice to have a read-only view without the additional properties.

**Comment by srdanrasic** [comment]
There isn't an easy solution for that :( We could add overload for `flatMapLatest` that returns ObservableArray, but then one would expect the same for all other operators. That would be a bunch of overloads :)

You could implement something like:

```swift
extension SignalProtocol where Element: ObservableArrayEventProtocol, Error == NoError {

    func asObservableArray() -> ObservableArray<Element.Item> {
        let array = MutableObservableArray<Element.Item>([])
        map { ObservableArrayEvent(change: $0.change, source: $0.source) }.bind(to: array)
        return array
    }
}
```

(Unfortunately we have to map `ObservableArrayEventProtocol` to `ObservableArrayEvent`).

However, there are ownership issues with such approach. Returned `ObservableArray` is an instance, so unlike `Signal`, it will not live until it "completes" (because it completes when it dies). That means that you cannot just bind the returned array, you also have to keep a reference to it.

**Comment by tonyarnold** [comment]
No, that's OK — I understand what you're saying, and the "backing" `ObservableArray` seems to work just fine without considerable overhead, so I have an answer and am happy :+1:
