### ISSUE TITLE
Bond 6 discussion

### ISSUE THREAD

**Issue by srdanrasic** [ReactiveKit/Bond#342]
Hi Everyone!

After successful transition to Bond 5 and ReactiveKit we are ready to move forward. I'm opening an issue to discuss ideas and wishes for the next version of Bond. 

My primary focus is cleaning up the API. The `bnd_` prefix does not match established Swift naming conventions so all extension will be moved to a proxy type `ReactiveExtensions`. In practice, this means that `label.bnd_text` becomes `label.reactive.text`. I've already made much progress on this front.

I feel that Bond has stabilised enough and that we don't need to change any of the current concepts or deprecate existing types and functionalities. We'll be focusing on cleaning up the interface and improving existing stuff where needed.

Next version's working branch is `master`.

_Current status:_

- API cleanup 
  - Add `ReactiveExtensions` proxy type ✓
  - Move all extensions to the proxy ✓
  - Refine `Deallocatable` protocol

- Enhance UITable/UICollectionView bindings
  - Allow developer to override application of array events ✓
  - Refine the implementation

- Update and improve the documentation

_Expected release date:_ Early February 2017.

**Comment by tonyarnold** [comment]
One thing I'd like to suggest: make a single framework and test target, and allow them to target all valid platforms. I've done this for a number of libraries already, and it drastically simplifies maintenance and means you can just have a single scheme that can generate iOS, macOS, tvOS and watchOS. 

It'd require a little target/scheme restructuring, but I'm happy to do the work if this sounds like a good idea to you?

**Comment by srdanrasic** [comment]
Bond v6 is released!

Btw, let's keep the project structure as is for now. I like the concept of single architecture, but I worry that we might stumble upon some unknown issues. If it becomes prevailing variant in the community we'll reconsider the decision.
