### ISSUE TITLE
Remove batch of rows from a MutableObservable2DArray section

### ISSUE THREAD

**Issue by drw86312** [ReactiveKit/Bond#343]
Hello. I'm very new to Bond and I'm wondering if there is an easy way to remove all rows from a MutableObservable2DArray section? I tried writing my own function as an extension, but it crashes with "Index out of bounds" after 5 iterations (in a section with 7 items). I'd like to keep the section in my datasource (as I'd always like to display the header), while dynamically adding or removing a batch of rows. 

```
extension MutableObservable2DArray {

    func removeRowsIn(sectionIndex: Int) {
        guard let section = sections[safe: sectionIndex] else { return }
        batchUpdate { dataSource in
            section
                .items
                .enumerated()
                .map { IndexPath(row: $0.0, section: sectionIndex) }
                .forEach {
                    dataSource.removeItem(at: $0)
            }
        }
    }
}
```

**Comment by srdanrasic** [comment]
Whenever you remove an item, all items that follow are shifted one place left so eventually you'll try to remove item at non-existing index path. Therefore, you have to delete items in reverse order. If you do `reversed()` just before `forEach`, I think it should work.  

Anyway, it a helpful feature, so let's plan it as an enhancement :)

**Comment by drw86312** [comment]
Awesome! Thanks for the help.
