### ISSUE TITLE
How to know the deleted elements?

### ISSUE THREAD

**Issue by Bargetor** [ReactiveKit/Bond#344]
```
ArrayObservable.observeNext(with:{event in
    switch(event.change){
    case .deletes(let indexs):
        for index in indexs{
            let deletedElement = event.source[index] //index out of bounds
        }
        break
    default: break
    }
}
```

from the perspective of decoupling, the observer can not know the deleted element, only index.
how to know the deleted elements?

**Comment by Bargetor** [comment]
![image](https://cloud.githubusercontent.com/assets/8370612/21414443/6e38b2d4-c83a-11e6-8efa-a550d20d40e7.png)
the prevEvent.source and newEvent.source is same instance, I still can't to know

**Comment by srdanrasic** [comment]
You're right :( The only way to do it for now is to track previous state by yourself.
