### ISSUE TITLE
Use Diff.swift as a direct dependency?

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveKit/Bond#345]
I've been having some issues with the diff functionality in `ObservableArray` (it seems like it's not handling moves correctly under macOS SDK), and rather than trying to fix the code copied from Dwifft, I thought I might suggest using https://github.com/wokalski/Diff.swift as a proper dependency instead? 

It's significantly faster, and from a preliminary scan it appears to offer everything that Dwifft does.

What are your thoughts, @srdanrasic?

**Comment by srdanrasic** [comment]
The integrated diff algorithm does not support moves, everything is insert or delete.

From a quick look, Diff.swift looks interesting and much better solution. Let's add it as a todo for Bond 6.

**Comment by tonyarnold** [comment]
Sounds great. I'll probably pull together a PR shortly, as I have need of it in a client project now. 

Are you OK with introducing Diff.swift as a dependency (rather than pulling in the source directly as you did with Dwifft)? There are alternatives using CocoaPods or splitting out the ObservableArray diffing into a separate framework, but they would make it harder to just install and go.

**Comment by srdanrasic** [comment]
Implemented.
