### ISSUE TITLE
Bind Observable Bool to Image Hidden Attribute

### ISSUE THREAD

**Issue by cre8it** [ReactiveKit/Bond#348]
I'm sure I'm missing something small but kinda can't figure it out... 

In my ViewModel I have an Observable Bool:

`public var ProfileCompleted = Observable<Bool?>(false)`

In my View I have a UIImageView:

`@IBOutlet var ProfileCompletedImage: UIImageView!`

When I try to bind the observable bool to the bnd_isHidden of the ImageView the compiler spits an error that it expects a signal:

`viewModel.ProfileCompleted.bind(to: ProfileCompletedImage.bnd_isHidden)`

Any idea what I misunderstand?

Error: `**Incorrect argument label in call (have 'to:', expected 'signal:')**`

**Comment by cre8it** [comment]
Never mind, the error came because I declared my Bool as optional in my ViewModel... problem solved

**Comment by srdanrasic** [comment]
@cre8it, you can keep your optional if you do

```swift
viewModel.ProfileCompleted.ignoreNil().bind(to: ProfileCompletedImage.bnd_isHidden)
```

**Comment by cre8it** [comment]
@srdanrasic thanks for that hint, I will certainly keep it mind for cases where I need to have optionals ... great! Thanks
