### ISSUE TITLE
Build failing because of Bond when building Unit Test target

### ISSUE THREAD

**Issue by eMdOS** [ReactiveKit/Bond#350]
I created a `View Model` (I'm using MVVM) for a View Controller, and I'm binding some values from view model to my view controller.

Afterwards, I created an XCTestCase to test my view model. The thing is, when trying to build and run my test cases I'm getting:

```
ld: framework not found Bond for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It only happens when trying to run the unit tests target.... When running my app's target it works perfectly. 

(I'm using `Carthage` as package manager).

Thanks in advance.

**Comment by srdanrasic** [comment]
You need to link the frameworks with the test target too, like you did with the app target.
