### ISSUE TITLE
Value of type 'MutableObservableArray<String>' has no member 'lift'

### ISSUE THREAD

**Issue by arasu01** [ReactiveKit/Bond#375]
Hi,

I have following logic in my code:

```
let data = ObservableArray<String>()
data.append(AboutViewController.text)
        
data.lift().bindTo(tableView) { indexPath, dataSource, tableView -> UITableViewCell in
// My code here
}
```

Now I'm migrating to swift 3.0 so update the bond library. By Following migration guide I have changed the code as below: 

```
let data = MutableObservableArray<String>()
data.append(AboutViewController.text)
        
data.lift().bind(to: tableView) { indexPath, dataSource, tableView -> UITableViewCell in
// My code here
}
```

Now, Getting the following error 

> Value of type 'MutableObservableArray<String>' has no member 'lift'

How fix this issue? There is nowhere mentioned in document about this.

**Comment by srdanrasic** [comment]
Lift is not needed any more. Check out the example in readme :)

**Comment by arasu01** [comment]
Where there nothing related lift in the readme. Then how can I blindly check it? Since I'm new to this library.

**Comment by srdanrasic** [comment]
Since there are a lot of changes, I'd recommend rereading the README. There is an example of how to bind ObservableArray:

```swift
let posts: ObservableArray <[Post]> = ...

posts.bind(to: tableView) { posts, indexPath, tableView in
  let cell = tableView.dequeueCell(withIdentifier: "PostCell", for: indexPath) as! PostCell
  cell.post = posts[indexPath.row]
  return cell
}
```

Just remove the lift. Also, index path is now second argument of the closure instead of first.

**Comment by srdanrasic** [comment]
Lift was used to convert 1D array onto 2D arrays, but now you can use both 1D and 2D array without lifting.

**Comment by arasu01** [comment]
Thanks. Got it.
