### ISSUE TITLE
Migration to Bond 5. EventProducer to Signal?

### ISSUE THREAD

**Issue by aleos** [ReactiveKit/Bond#378]
How to replace old usage of EventProducer in terms of Signal?

**Comment by srdanrasic** [comment]
I'd go over ReactiveKit [readme](https://github.com/ReactiveKit/ReactiveKit) and see how Signal works.

If you need specific advice, please post a code sample.

**Comment by aleos** [comment]
Here is an example:
```
var bnd_lastDeal = EventProducer<Deal>()
bnd_lastDeal.next(deal)
bnd_lastDeal.observe { (deal) in
    ...
}
```

**Comment by iandundas** [comment]
`SafePublishSubject` can be used in the same way

**Comment by srdanrasic** [comment]
@iandundas is right, additionally you can also use SafeReplaySubject to get previously sent events as in your example.

```
var bnd_lastDeal = SafeReplaySubject<Deal>()
bnd_lastDeal.next(deal)
bnd_lastDeal.observeNext { (deal) in
    ...
}
bnd_lastDeal.bind(to: view.bnd_lastDeal) // signal only new values
```

**Comment by aleos** [comment]
@iandundas , @srdanrasic Thank you very much! It is great!
