### ISSUE TITLE
UITextField.reactive.text bug? 

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/Bond#379]
Hey! I might have found something, I've narrowed it down to the following: 

Say we have an observation of a UITextField:

```swift
textField.reactive.text.observeNext { (value) in
     print("Field updated: \(value)")
}.dispose(in: reactive.bag)  
```

If I put the following beneath it: 

```swift
Signal.just("Immediate").bind(to:textField.reactive.text)
```

Then the output is as expected: 

    Field updated: Optional("")
    Field updated: Optional("Immediate")

*However*, if I instead put the following beneath it: 

```swift
Signal.just("Later").delay(interval: 1).bind(to:textField.reactive.text)
```

Then the (only) output is: 

    Field updated: Optional("")
    Field updated: Optional("")

Interestingly, in both cases the TextField does actually show the change, just not via the `reactive.text` events. So, something fishy going on with the delay there. NB it's not the `delay` itself, - I found this due to the inherent delay of a network request. But the delay simulates it.

**Comment by iandundas** [comment]
This is in 6.0.0-beta.3

**Comment by iandundas** [comment]
Wait you released 6.0 proper - I'll check with that

**Comment by srdanrasic** [comment]
Truth is, it was not intended to work that way. It's strange that your received "Immediate" in first example.

`textField.reactive.text` fires an event when it receives `UIControlEvents.allEditingEvents`, but that event is not being send when we update `textField.text` from the binding. 

In other word, DynamicSubjects fire only on user events. We could reconsider this decision, but I'll need to confirm it does not have any unintended side-effects.

**Comment by iandundas** [comment]
Okay good to know - thanks! I've reworked what I was doing a bit to use bidirectional binding instead, and that works great. Cheers man.
