### ISSUE TITLE
Bond for RxSwift

### ISSUE THREAD

**Issue by SPopenko** [ReactiveKit/Bond#380]
Hi guys, 
Does it make any sense to try using Bond as binding framework if we already have RxSwift on board? 
Bond definitely has much nicer syntax and it's interesting to try it. But RxSwift  was integrated deep enough to the project to migrate on ReactiveKit. 

Any recommendations?

**Comment by srdanrasic** [comment]
The two frameworks solve the same problem in slightly different ways so using them both in the same project would be redundant (unless during the transitional phase).

If you already have RxSwift deeply integrated and don't think that nicer syntax is worth the migration, I'd just keep it as is. RxSwift a great framework and you might get some of Bond's syntax features with few extensions of your own.

**Comment by SPopenko** [comment]
@srdanrasic thank you for your quick reply. I would agree :)
