### ISSUE TITLE
Crash in dealloc/deinit when using keyPath()

### ISSUE THREAD

**Issue by LakhV** [ReactiveKit/Bond#382]
### Swift class:
```swift
class SwiftTestClass: NSObject {
  dynamic var property: Any! = "SwiftTestClass"
  deinit {
    print(property as! String)
  }
}
```

### ObjC class:
```objc
.h
@interface ObjcTestClass : NSObject
  @property (nonatomic) NSString *property;
@end

.m
@implementation ObjcTestClass
- (instancetype)init {
  self = [super init];
  _property = @"ObjcTestClass";
  return self;
}

- (void)dealloc {
  [self method];
}

- (void)method {
  NSLog(@"%@", self.property);
}
@end
```

### Test:
```swift
@objc
class Test {
  var swiftTestObject: SwiftTestClass!
  var objcTestObject: ObjcTestClass!

  func test () {
    swiftTestObject = SwiftTestClass()
    objcTestObject = ObjcTestClass()

    swiftTestObject.reactive.keyPath("property", ofType: String.self)
    .observeNext { str in
      print(str)
    }

    swiftTestObject.property = "New SwiftTestClass value"

    objcTestObject.reactive.keyPath("property", ofType: NSString.self)
    .observeNext { str in
      print(str as String)
    }

    objcTestObject.property = "New ObjcTestClass value"

    swiftTestObject = nil
    objcTestObject = nil
  }
}
```

## Actual result:
(console output)
_SwiftTestClass
New SwiftTestClass value
ObjcTestClass
New ObjcTestClass value
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SwiftTestClass method]: unrecognized selector sent to instance 0x618000078fc0_

Crash happens here "swiftTestObject = nil". For some reason it calls dealloc method of ObjcTestClass instead of deinit of SwiftTestClass, but the instance (self) is swiftTestObject - I set a break point in the dealloc method. Since ObjcTestClass dealloc calls [self method] which is not method of SwiftTestClass the "unrecognized selector sent to instance" exception throws.
<img width="351" alt="debug" src="https://cloud.githubusercontent.com/assets/6638541/22830122/048f83da-efae-11e6-8696-bf1d3b6b2bba.png">

If I swap 2 last lines like
```swift
objcTestObject = nil
swiftTestObject = nil
```

then deinit of SwiftTestClass class called for objcTestObject instance which also leads to crash.

If I comment out either swiftTestObject.reactive.keyPath() or objcTestObject.reactive.keyPath() call dealloc/deinit called as expected.

## Expected result:
No crashes )

Any suggestions about a hotfix?
Thanks.

**Comment by srdanrasic** [comment]
@LakhV, thanks for such a detailed issue report! :)

Yes, seems this was a bug in Bond. I've just released v6.0.1 that should fix this.
