### ISSUE TITLE
How to replicate old observeNew behavior?

### ISSUE THREAD

**Issue by DimaVartanian** [ReactiveKit/Bond#384]
Apologies in advance if this is in the wrong place or if this is answered somewhere else because I did look and could not find a concrete answer to the question (I also wasn't sure if I should maybe post this in the ReactiveKit repo instead).

I am currently working on a Swift 2>3 migration in an app that uses Bond and dealing with updating the observation calls.

`observe` is now `observeNext` and `observeNew` is gone. What I am trying to do is add an observer that will ignore any previous elements and only respond to new ones from the time the observer is added and I'm not seeing a way to do that. Someone else asked the question and figured out that they can use the `skip` function but as far as I can see that only lets you specify the first or last `n` elements to ignore. What I am trying to do is ignore any already existing elements and case about new ones going forward regardless of how many already exist, which as far as I can tell is what `observeNew` did before.

**Comment by iandundas** [comment]
Hey, I'm not sure about older versions of Bond, but to answer your question:

.observe gives you `Event`s, where `Event` is an enum defined as: 

```swift
enum Event<Element, Error> where Error : Error {
    case next(Element)
    case failed(Error)
    case completed
}
```

So Event can either be .next(let value), .completed or .error(let error).

`.observeNext` gives you just the `.next` case's value directly, and is just a convenience method really (you can also `observeCompleted`, for example).

Both - in the general case - give you values from the time that you observe the signal.

**Comment by DimaVartanian** [comment]
Hi, thanks for the response! I actually just tested this and it is not exactly the case. To summarize, when you add an observer to a normal observable/property, by default the block will fire once immediately using the last value from the observable. As such, just doing `skip(first: 1)` does the trick here by ignoring just that existing value and firing for everything going forward. In any case, thanks for the help! I consider this closed now.
