### ISSUE TITLE
MVVM dirty check

### ISSUE THREAD

**Issue by jordancamara** [ReactiveKit/Bond#389]
Let's say that you have `class FoobarViewModel {
       var name = Observable<String>()
       var phone = Observable<String>()
       ...
}`

... How do you check whether the object itself has changed? 

One of the things I'm struggling with right now is showing something on the screen when any of the object's sub properties have changed.

Any thoughts?

**Comment by srdanrasic** [comment]
Changing properties (observables) does not change to owner object so there is no way to observe changes of FoobarViewModel instance. However, Observables are Signals, so if you also `import ReactiveKit`, you can do 

```swift
merge(name, phone, ...).observeNext { _ in 
  // either name or phone changed
}
```

to get notified when either of the properties change. If you care about individual properties values, you probably want:

```swift
combineLatest(name, phone, ...).observeNext { (name, phone) in 
  // either name or phone changed (at least once)
}
```

**Comment by jordancamara** [comment]
That helps a lot.

How do you remove an binding on UITextField's bnd_controlEvents? I am needing to dynamically set this.

**Comment by jordancamara** [comment]
Nevermind. I think I found my own solution. Using dispose bags now. Thanks.
