### ISSUE TITLE
Exception on TableView binding if array was changed on other Thread

### ISSUE THREAD

**Issue by nidomiro** [ReactiveKit/Bond#390]
I just encountered the problem, that an exception (by iOS) is thrown if the array was updated in an multi-threaded environment.
I think the problem is, that the Array is altered again, before the TableView receives the update.

I'm using 'Bond', '~> 5.4'
The Exception occurs at UITableView.swift:142

    *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.6.22/UITableView.m:1396
    *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert row 1 into section 0, but there are only 1 rows in section 0 after the update'

My Setup:

    class A {
        
        // !only one element allowed! will contain the most recend added object only!
        let files = MutableObservableArray([URL]())
        let disposeBag = DisposeBag()
        
        init() {
            self.files.observeNext(with: {
                [unowned self] _ in
                if self.files.count > 1 {
                    self.files.replace(with: [self.files.array.last!])
                }
            }).dispose(in: self.disposeBag)
        }
        
    }

The TableView binding:

    override func viewDidLoad() {
            super.viewDidLoad()
            // Same result without the '.observeOn(DispatchQueue.main)'
            self.a.files.observeOn(DispatchQueue.main).bind(to: self.filesTableView) {
                [weak self] array, indexPath, tableView in
                    ...
            }
            
    }

**Comment by srdanrasic** [comment]
There were some issues with the diffs in v5. It's fixed in v6.

It would be too hard to apply the fix to v5 so your best course of action would be to update.
