### ISSUE TITLE
Code from Readme doesn't compile - Binding Observable Arrays

### ISSUE THREAD

**Issue by alistra** [ReactiveKit/Bond#393]
This piece of code from the Readme.md doesn't compile. It is supposed to bind the mutable observable array to the observable array after a `map`.

    let names = MutableObservableArray(["Steve", "Tim"])
    let nameLengths = ObservableArray<Int>()
    names.map { $0.characters.count }.bind(to: nameLengths)

![screen shot 2017-03-01 at 14 33 24](https://cloud.githubusercontent.com/assets/233144/23462003/67757b20-fe8c-11e6-98e1-9a4997ff5f2e.jpg)

Did the API change? Or is this a bug?

**Comment by mkalinowski** [comment]
@alistra: The following code works:

```
let names = ObservableArray(["Steve", "Tim"])
let nameLengths = MutableObservableArray<Int>()
names.map { $0.characters.count }.bind(to: nameLengths)
```

**Comment by srdanrasic** [comment]
Yeah, it should have said MutableObservableArray. It's fixed, thanks :)
