### ISSUE TITLE
Issue with MutableObservableArray .replace

### ISSUE THREAD

**Issue by Joebayld** [ReactiveKit/Bond#396]
I've noticed that when I bind an array to an NSTableView then replace the objects in the array, the table doesn't update.. But if I iterate the objects in the array and append them, the table does update.

The follow doesn't work.
```swift
container.replace(with: nodes)
```
The following works.
```swift
container.removeAll()
for node in nodes {
    container.append(node)
}
```

**Comment by feighter09** [comment]
cmd + click the `replace` method. Does it bring you to 
```
public func replace(with array: [Item])
```
or 
```
/// Replace all emitted elements with the given element.
public func replace<T>(with element: T) -> ReactiveKit.Signal<T, Self.Error>
```

It's very easy to accidentally be using the latter when types don't match up exactly right, in which case the method acts very differently than you'd expect

**Comment by daviskoh** [comment]
im seeing

```
public func replace(with array: [Item])
```

but the collection view still does not update
