### ISSUE TITLE
Compiling on Xcode 8.3

### ISSUE THREAD

**Issue by michaellatman** [ReactiveKit/Bond#397]
Has anyone gotten this compiled on Xcode 8.3? It seems to have trouble compiling the diff library.

**Comment by tonyarnold** [comment]
Hi Michael, can you check which version of Bond and Diff.swift you're using? There were issues compiling Diff.swift under early betas of Xcode 8.3, but I believe the Swift team fixed those a couple of betas ago.

**Comment by tonyarnold** [comment]
Actually, bear with me - the fixes to Diff.swift aren't in a release yet. We'll get this sorted shortly, but in the meantime you can reference https://github.com/wokalski/Diff.swift/pull/49 for more details.
