### ISSUE TITLE
Remove observers when screen is not visible anymore

### ISSUE THREAD

**Issue by kevinvugts** [ReactiveKit/Bond#401]
Hi guys,

How am I able to remove the observers I am listening for in my ViewController when I navigate to an other screen?

Looking forward for the solution!

Cheers,
Kevin.

**Comment by srdanrasic** [comment]
Hi @kevinvugts,

Check out ReactiveKit docs on [Disposing](https://github.com/ReactiveKit/ReactiveKit/blob/master/README.md#-disposing-signals) and see if that helps.
