### ISSUE TITLE
Tap extension for UIBarButtonItem improvements

### ISSUE THREAD

**Issue by grzegorzkrukowski** [ReactiveKit/Bond#402]
Hey

While working with Bond I found it really confusing that example taken from README is behaving like this:

```
button.reactive.tap
  .observe {
    print("Button tapped.")
  }  
```

Problem here is that .observe on `UIBarButtonItem` is getting called also when the `UIBarButtonItem` gets deallocated with `completed` signal being passed.

The solutions for current code base are:

1. use observeNext() to make sure it only react on next signals

2. Check the type of event being passed to observe.

```
button.reactive.tap.observe {event in
    switch event {
        case .next(let _):
            print("Button tapped.")
        break;
        default:
        break;
    }
}
```

I was expecting to have "tap" observer only being called on real "taps" - maybe it can be fixed inside Bond sources to filter the type of events already there.

**Comment by srdanrasic** [comment]
Thanks for reporting this @grzegorzkrukowski. The right solution here is to use `observeNext` as you pointed out. I'll update the documentation.
