### ISSUE TITLE
KVO on background queues

### ISSUE THREAD

**Issue by alistra** [ReactiveKit/Bond#403]
Hey I have a question.

I wanted to use `DynamicSubject2` to listen to KVO changes and generate signals, but it only works on the main thread (`ImmediateOnMainExecutionContext` in the `bind(signal:)` implementation).

Is there any way to actually use `DynamicSubject2` to listen on KVO on a background queue. I'm asking because I have core data assertions (https://oleb.net/blog/2014/06/core-data-concurrency-debugging/) and my managed object accesses have to be done on a specific queue, bound to the context of the managed object.

I'm thinking about doing my own version of 

    public func keyPath<T>(_ keyPath: String, ofType: T.Type) -> DynamicSubject<T>

that takes an additional `ExecutionContext` argument and wraps the getter & setter with it. Are there any unforeseen caveats with this? Or this just wasn't needed, so it wasn't implemented?

Edit: It's not easily doable, as `RKKeyValueSignal` is `private`.

**Comment by srdanrasic** [comment]
Hey @alistra 

Main queue is enforced only in the binding, i.e. only when you bind a signal to DynamicSubject. If you observe DynamicSubject you are observing on the thread wherever the events are sent from.

```swift
let subject = object.keyPath(...)

subject.observeNext {
   // called wherever KVO's `observeValue(forKeyPath:of:change:context:)` was called from
}

// However:
someSignal.bind(to: subject) // will update subject on .main

// You can do following instead:
someSignal.observeOn(.background).observe(with: subject).dispose(in: bag) 
```

However, you have a good point. Bindings should not be limited to main queue. I have an update in plan that will allow bindings to be used on other queues / threads.

**Comment by alistra** [comment]
From what I understand the `bind` method has an `ExecutionContext` parameter, so it shouldn't be needed to use the `ImmediateOnMainExecutionContext` there.

**Comment by srdanrasic** [comment]
I've just released v6.2.0 with support for bindings from other threads. This also upgrades KVO methods to support other context.

```swift
func keyPath<T>(_ keyPath: String, ofType: T.Type, context: ExecutionContext? = nil)
```

For example, to update from wherever the signal is sending, do

```swift
object.keyPath("name", ofType: String.self, context: .immediate)
```

To update from background queue, do

```swift
object.keyPath("name", ofType: String.self, context: .background)
```

Default updates on main queue.

```swift
object.keyPath("name", ofType: String.self)
```

Here is more on the implementation:
https://github.com/ReactiveKit/ReactiveKit#binding-targets

**Comment by alistra** [comment]
Really awesome changes!

I would narrow down the compliance to `BindingExecutionContextProvider` to `UIView` and `UIViewController` (or all base UIKit classes for which it makes sense), because currently you can't override the conformance to something deriving from `NSObject`

I'm trying to do something like this, but it errors out on not being able to override it.
The errors say "Overriding non-open var outside its defining module" and 
"Declarations in extensions cannot override yet"
```
extension NSManagedObject {
    override var bindingExecutionContext: ExecutionContext {
        return (managedObjectContext?.perform).flatMap { ExecutionContext($0) } ?? .immediate
    }
}
```

I think changing it to open won't work, as the second error says you can't override from an extension.

**Comment by srdanrasic** [comment]
Thanks @alistra! You are right, I will probably have to narrow the conformance to UIKit objects. I really thought I tested extension override, but apparently I did not :) Narrowing the conformance seems like to right thing to do anyway. I will make the changes tonight.

**Comment by srdanrasic** [comment]
Check out v6.2.0 @alistra. I think this should be it :)
