### ISSUE TITLE
Support for binding to accessibilityIdentifier

### ISSUE THREAD

**Issue by lucianomarisi** [ReactiveKit/Bond#404]
It would be nice if Bond allowed binding to `accessibilityIdentifier`.

Currently I've added this extension for `UIView`in my project:

```swift
extension ReactiveExtensions where Base: UIView {

	var accessibilityIdentifier: Bond<String?> {
		return bond {
			$0.accessibilityIdentifier = $1
		}
	}

}
```

It would probably be best to figure out a way to add it on `NSObjectProtocol` where the `accessibilityIdentifier` is defined and make this part of Bond. Unfortunately, I could not figure out how to do this otherwise I would have put a PR.

**Comment by srdanrasic** [comment]
Thanks for suggestion @lucianomarisi! It's implemented in latest version. https://github.com/ReactiveKit/Bond/blob/master/Sources/Bond/UIKit/UIAccessibilityIdentification.swift

**Comment by lucianomarisi** [comment]
Thanks, very elegant solution, and today I learned about the `UIAccessibilityIdentification` protocol`!
