### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveKit/Bond#406]
So I thought I'd cleared up Swift Package Manager support in 6.2.2, however it appears that there is a rule we're "breaking":

> Directories under Sources/ acts as Swift modules. The rules for layouts is here: https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#module-format-reference

So in order to support Swift Package Manager for Bond, the `Sources` directory needs to contain all of the source files. 

I'm happy to draw up the PR for this, but I wanted to check if it was something you were keen to pursue first, @srdanrasic.

**Comment by srdanrasic** [comment]
Damn Xcode that does not support support Swift modules properly.

I'm ok with having everything in one directory, but it will be harder to define Podspec excludes for iOS/macOS. Any ides on that?

**Comment by tonyarnold** [comment]
Not really, I'll have to manually exclude where appropriate. I'm almost finished drawing up a PR, then we can discuss if and how to proceed.

**Comment by tonyarnold** [comment]
I've got this building under Swift Package Manager, there are a few limitations:

- It's macOS only right now - that's a limitation of Swift Package Manager
- It requires manually excluding individual sources for AppKit/UIKit in the Podspec

Based on the proposals, it looks like Swift Package Manager v4 will be a more rounded release and will likely support everything needed, but right now, it's more of an interesting experiment than a production-ready package manager (at least for apps - it seems like sadly, it is heavily targeting backend/server-based targets?).

I'm still happy to create the PR - I'd love to use Swift Package Manager in my macOS projects - but I don't want to make your work harder. What are your thoughts, @srdanrasic?

**Comment by srdanrasic** [comment]
Hey @tonyarnold,

Yeah, I've been reading more about SPM. It still is very experimental. I'm surprised it's evolving so slowly. Carthage for example was up and running in half of that time.

What if we move everything from `Sources` to `Sources/Bond`? That way we would have module `Bond` that can have arbitrary number of subdirectories - which are not treated as modules. We could then add exclude directory `Sources/Bond/UIKit` to Package.swift.

Alternative approach could be flattening the directory structure and using configuration macros `#if os(iOS) / os(tvOS) / os(macOS)` in all files. We could then have all files part of all targets. That would make both SPM and CocoaPods simpler to manage. I might actually be in favour of this approach. What do you think?

One thing still remains. How do we handle `BNDProtocolProxyBase` class that is written in ObjC.

**Comment by tonyarnold** [comment]
OK, see #408 for the implementation I came up with. It's a bit of a hybrid of both approaches we discussed above, but does work for all the scenarios.

**Comment by srdanrasic** [comment]
Released as 6.2.3.
