### ISSUE TITLE
Retain scroll position in tableview after changing datasource

### ISSUE THREAD

**Issue by pk1** [ReactiveKit/Bond#407]
Hi,

I'm currently trying to implement a pagination for my tableview. After the user starts to scroll the tableview I check if he reaches the end if so I load in the background additional content which will be appended to the tableviews datasource (MutableObservableArray). The pagination mechanism is working so far but what keeps me banging my head is why the scroll position is not retained while I append additional items to my datasource?

What happens is that if the user reaches the end (5 items\records before the real end) that I'm starting to load the next 20 records to the datasource. While the new records are appended to the datasource, the scroll position gets lost and suddenly the user sees different records in the table view.

To be more precise:

1. first 20 records are loaded and the first approximately 3 records are visible in the table view (the tableview is sized over the whole screen but I'm presenting the records as cards which a dynamic height )

2. user starts to scroll now

3. if user reaches the 15th record (still 5 more to show) I start to load additional 20 records from the database and append them to the end of the datasource

4. now it seems that instead of showing the user still the 15th or lets say 16th or 17th card, he suddenly sees card 25

In the meantime I have fixed that so far by using beginUpdates and endUpdates in addition to saving the content offset of the tableview before appending new data and using also reloadData(). But the user experience is not really what I expected and I'm not sure if this is a general Swift problem or If I somehow use the wrong approach with Bond to solve my problem?

Some code which shows a part of the loadMoreData function:

```swift
DispatchQueue.global(qos: .background).async {
                
                let verticalContentOffset  = tableView.contentOffset.y;
                
                DispatchQueue.main.async{
                    tableView.beginUpdates()
                }

                //load records from the database

                for record in records {
                        //do some further enrichment

                        //finally append to the datasource
                       DispatchQueue.main.async{
                             self.dataSource.append(record)
                       }
                 }

                 DispatchQueue.main.async{
                    tableView.endUpdates()
                    tableView.setContentOffset(CGPoint(x:0, y:verticalContentOffset), animated: false)
                    tableView.reloadData()
                }
}
```

Update -> this is how I bind the datasource to the tableview:

```swift
ListViewModel.shared.dataSource.bind(to: cardsTableView) { dataSource, indexPath, tableView in
}
```

**Comment by srdanrasic** [comment]
Hi @pk1,
 
Can you try with non-animated binding: `bind(to: cardsTableView, animated: false) { ... }`. UITableView does not really work well when appending a lot of items at the end.

Next thing I would try is saving the content offset in reloadData. Make a subclass of UITableView and override reloadData.

```swift
class MyTableView: UITableView {

    override func reloadData() {
        let offset = contentOffset
        super.reloadData()
        contentOffset = offset
    }
}
```

Use your subclass instead of UITableView to instantiate the table view then.

Note that reloadData is called only if binding is non-animated or if you use `replace` method instead of `append`:

```swift
dataSourceArray.replace(with: dataSourceArray.array + newPageArray)
```

**Comment by pk1** [comment]
Thanks for the quick reply @srdanrasic (appreciate it)!

I refactored my code according to your proposals and it seems that it did the trick.  At least it looks promising on the first few tests I did. Will have a deeper look and try also if maybe only using the non-animated-binding is the solution (at the moment I'm using the non-animated binding and the UITableView subclass)

**Comment by willjstevens** [comment]
Hi @pki , would you be willing to post the portions of code relevant to your tableview setup with Bond?  I am trying to do similar but struggling, after following the documentation and table view unit test. 

I also posted on SOF: http://stackoverflow.com/questions/43150045/reactivekit-bond-uitableview-not-updating

**Comment by pk1** [comment]
I think we should continue this discussion in SOF because it has nothing to do with the issue in this thread.

**Comment by khachaturxamlab** [comment]
But It is not solution.
I use local filter in my code.
I have initialItems and filteredItems.
I always display filteredItems.
And I do this with binding from filteredItems. 
When I scrolled and after that filtered Items.
New Filtered Items Displayed, But conetentOffset of tableView not zero.

**Comment by HarshadAtMobio** [comment]
let offset = tableview.contentOffset
        UIView.animate(withDuration: 0) {
            self.tableview.reloadData()
        }
        tableview.layoutIfNeeded()
        DispatchQueue.main.async {
            self.tableview.contentOffset = offset
        }

I faced same issue and get this solution. Hope it helps you to.
