### ISSUE TITLE
Creating a MutableObservableArray object with generics throws Segmentation fault on build

### ISSUE THREAD

**Issue by Burtan** [ReactiveKit/Bond#409]
Hi,

the following code throws an exception in my project where Bond 6.2.1 is added as a pod
`let bla = MutableObservableArray<String>()`
So you cannot create an empty object

**Comment by srdanrasic** [comment]
Hi @Burtan,

It's a bug in Swift compiler. You can avoid it by passing initial value:

```swift
let bla = MutableObservableArray<String>([])
```

**Comment by Burtan** [comment]
Thanks for the info! Pretty annoying bug, took me some time to find out. Maybe you could add a hint into the documentation until it is fixed.

**Comment by srdanrasic** [comment]
You are right, I should. Btw, are you on Xcode 8.3?

**Comment by Burtan** [comment]
Nope, not yet. Maybe it's fixed

**Comment by srdanrasic** [comment]
Yeah, seems to be fixed :)

**Comment by Burtan** [comment]
Good to know :-). Anyway thanks for the fast response!
