### ISSUE TITLE
Internal API crash on Xcode 8.3

### ISSUE THREAD

**Issue by natalia-osa** [ReactiveKit/Bond#410]
I'm getting a crash after upgrading to Xcode 8.3 (Swift 3.1 instead of 3.0.1). With previous version everything was working fine.

It seems there's a problem with a private property/iVAR called `__TF11ReactiveKitau31ImmediateOnMainExecutionContextFFT_T_T_`.

I get following crash:

```
dyld: lazy symbol binding failed: Symbol not found: __TF11ReactiveKitau31ImmediateOnMainExecutionContextFFT_T_T_
  Referenced from: /.../Library/Developer/CoreSimulator/Devices/FEC21F04-BA6C-4345-8803-D4D2C0690998/data/Containers/Bundle/Application/8A3F479A-0C53-47AA-B36C-697E5AF2BB16/MYAPP.app/Frameworks/Bond.framework/Bond
  Expected in: /.../Library/Developer/CoreSimulator/Devices/FEC21F04-BA6C-4345-8803-D4D2C0690998/data/Containers/Bundle/Application/8A3F479A-0C53-47AA-B36C-697E5AF2BB16/MYAPP.app/Frameworks/ReactiveKit.framework/ReactiveKit

dyld: Symbol not found: __TF11ReactiveKitau31ImmediateOnMainExecutionContextFFT_T_T_
  Referenced from: /.../Library/Developer/CoreSimulator/Devices/FEC21F04-BA6C-4345-8803-D4D2C0690998/data/Containers/Bundle/Application/8A3F479A-0C53-47AA-B36C-697E5AF2BB16/MYAPP.app/Frameworks/Bond.framework/Bond
  Expected in: /.../Library/Developer/CoreSimulator/Devices/FEC21F04-BA6C-4345-8803-D4D2C0690998/data/Containers/Bundle/Application/8A3F479A-0C53-47AA-B36C-697E5AF2BB16/MYAPP.app/Frameworks/ReactiveKit.framework/ReactiveKit
```

Everything happens under such command:
```
viewModel.activityTypeImage.bind(to: activityImageView.bnd_image)
```

Where:
```
Printing description of activityImageView:
<UIImageView: 0x7fb953143980; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CALayer: 0x608005c3de40>>
Printing description of viewModel.activityTypeImage:
<Property<Optional<UIImage>>: 0x60000744f060>
```

It calls the implementation of `observeNext` function and crashes here:
```
    if case .next(let element) = event {
        observer(element) // crash SIGABRT
      }
```

-- edit --

I also did bump the version from 5.0.0 to 5.4.6. To test what's the fault, I reversed the version to 5.0.0 and it's still crashing, so I suppose the problem is connected rather with Swift 3.1 update then Bond update. 

On version 5.0.0 even the build doesn't work properly (crashes on start) and  the following output is shown (slightly different but still more or less similar):

```
dyld: Symbol not found: __TWau0_R_s5ErrorrGC11ReactiveKit17_ReplayOneSubjectxq__S0_14SignalProtocolS0_
  Referenced from: /.../Library/Developer/CoreSimulator/Devices/FEC21F04-BA6C-4345-8803-D4D2C0690998/data/Containers/Bundle/Application/86EC4449-D345-4BF0-A972-C9E3B077B4AC/MYAPP.app/Frameworks/Bond.framework/Bond
  Expected in: /.../Library/Developer/CoreSimulator/Devices/FEC21F04-BA6C-4345-8803-D4D2C0690998/data/Containers/Bundle/Application/86EC4449-D345-4BF0-A972-C9E3B077B4AC/MYAPP.app/Frameworks/ReactiveKit.framework/ReactiveKit
 in /.../Library/Developer/CoreSimulator/Devices/FEC21F04-BA6C-4345-8803-D4D2C0690998/data/Containers/Bundle/Application/86EC4449-D345-4BF0-A972-C9E3B077B4AC/MYAPP.app/Frameworks/Bond.framework/Bond
```

**Comment by srdanrasic** [comment]
Hi @natalia-osa,

Thanks for the detailed issue! I've experienced something similar once and the solution was to clear Carthage caches and rebuild. Cache is located at `~/Library/Caches/org.carthage.CarthageKit`.

However, I think there might be another problem because of updates to ReactiveKit. The best long-term solution would be to update Bond to latest v6, but I'm going to make an update to v5 that fixes ReactiveKit compatibility.

Give me few minutes.

**Comment by pixelrevision** [comment]
This looks like an issue with the dependency on ReactiveKit.  Initially I was able to create a cocoapods project and it pulled ReactiveKit (3.1.1) and things worked fine.  After updating my pod repos it started using ReactiveKit (3.5.1) which emits the same issue.

**Comment by srdanrasic** [comment]
Ok, @natalia-osa @pixelrevision, I've just released 5.4.7 that fixes the issue. Please try updating the dependencies.

**Comment by natalia-osa** [comment]
Thank you for awesome & fast support! Version 5.4.8 works perfectly, issue cannot be reproduced any more.

**Comment by srdanrasic** [comment]
Great to hear that! :)
