### ISSUE TITLE
No such module 'BNDProtocolProxyBase' error in 6.2.3

### ISSUE THREAD

**Issue by rvangraan** [ReactiveKit/Bond#411]
After the introduction of the `BUILDING_WITH_XCODE` directive here: , 
https://github.com/ReactiveKit/Bond/blob/3c553caabd628ad04efeb6d9ecb9b45cc7a74717/Sources/Bond/ProtocolProxy.swift#L29

our product is breaking with this error:

![screen shot 2017-04-04 at 14 43 09](https://cloud.githubusercontent.com/assets/2574318/24659597/0bad456a-1945-11e7-8972-6479b74550ea.png)

We are using CocoaPods version 1.2.1.beta.1 and importing the latest version:

```    pod 'Bond'```

**Comment by srdanrasic** [comment]
That is very strange since we are setting the configuration flag/directive in Podspec. 

I'll look into this later today.

**Comment by srdanrasic** [comment]
Hi @rvangraan,

I just tried creating a new project and installing Bond via CocoaPods from scratch and everything went fine.

The directive is properly defined in Podspec: https://github.com/ReactiveKit/Bond/blob/master/Bond.podspec#L29

Do you maybe have some kind of custom CocoaPods integrations or anything that might affect build settings?

If you do have custom build configuration that overrides CocoaPods' ones, make sure that `SWIFT_ACTIVE_COMPILATION_CONDITIONS` setting contains constant `BUILDING_WITH_XCODE`.

**Comment by nabileisa** [comment]
Hi, I have the same problem , tested with brand new project and default configuration using  .
 CocoaPods version 1.2.0 & xcode 8.3  and `pod 'Bond'`

**Comment by srdanrasic** [comment]
Hi @nabileisa, would be be able to send a demo project where this is happening? When I create a new project and add Bond pod I have no issues compiling it.

**Comment by nabileisa** [comment]
Hi @srdanrasic 
I have attached an Example project in the following link , this a simple project with just Bond installed and nothing else , and the build fails with the error posted in the original issue.
[bondapp.zip](https://github.com/ReactiveKit/Bond/files/902553/bondapp.zip)
hope it helps, and if I'm doing something wrong please let me know .

**Comment by srdanrasic** [comment]
Thanks @nabileisa, that helped a lot! 

Looks like there is an issue with CocoaPods not correctly setting `SWIFT_ACTIVE_COMPILATION_CONDITIONS`. I've worked around this by using `OTHER_SWIFT_FLAGS` instead for now.

Please try 6.2.4.

**Comment by nabileisa** [comment]
Tested with 6.2.4 and i can confirm now that the build succeeds and the issue is resolved, thank you for the great work .
