### ISSUE TITLE
ObservableArray bound on table view reports wrong number of items

### ISSUE THREAD

**Issue by softvision-catalinmustata** [ReactiveKit/Bond#412]
I have an `ObservableArray<ObservableArray<LayerCellDescriptorProtocol>>`bound to a UITableView, using a custom implementation of `TableViewBond` which crashes inside `cellForRow(at:)` while trying to access the dataSource (namely inside the subscript operator for `ObservableArray`)

While debugging, I've noticed the dataSource reports erroneous values for `numberOfItems(inSection:)` and therefore tries to create a cell using an indexPath that's out of range.

I'm using Bond 6.2.1, but I've also tried updating to 6.2.3 without success.

**Comment by srdanrasic** [comment]
Are you trying to implement table view with multiple sections? In that case I would suggest looking into `Observable2DArray`. 

`ObservableArray` containing other `ObservableArray`s cannot be used to achieve table view with multiple sections.

**Comment by softvision-catalinmustata** [comment]
Yes, it looks like that. I'm working on migrating this older project that wasn't developed by me and I'm still trying to get a grip on the whole logic. 

I'll try to move everything towards an `Observable2DArray`. However, I'm a bit confused as to why `ObservableArray`s do not work for this, as they do implement `DataSourceProtocol`, which has both `numberOfItems(inSection:)` and `numberOfSections`.

**Comment by srdanrasic** [comment]
ObservableArray containing other ObservableArrays is a very complex structure and it would be hard to implement proper bindings with multiple sections. In conformance to `DataSourceProtocol`, ObservableArray always returns 1 for `numberOfSections`.

Hopefully you'll get it up and running with `Observable2DArray`. It should be much simpler to manage. Feel free to ask more questions if something is unclear :)
