### ISSUE TITLE
bidirectionalMap does not bind

### ISSUE THREAD

**Issue by mohojojo** [ReactiveKit/Bond#421]
Hi!

I have a bidirectional map

```swift
var twoWayText = Observable<Int?>(8)

twoWayField.reactive.text.bidirectionalMap(to: { Int($0!)! }, from: { "\($0)" }).bidirectionalBind(to: mainVM.twoWayText)
```

but it does not works, the get/set methods in the map are not fire
maybe i'm missing something

**Comment by mkeiser** [comment]
I have the same issue. Is there a solution for this?

**Comment by tonyarnold** [comment]
I'm seeing similar here, too, I'll have a look and see what's changed.

**Comment by daviskoh** [comment]
any udpates?

**Comment by srdanrasic** [comment]
Fixed in latest release! Thanks for reporting the issues and waiting.

**Comment by asen-oit** [comment]
How to do bidirectionalBind from a Int property in model to UITextFiled?
