### ISSUE TITLE
compile error in NSObject+KVO.swift file

### ISSUE THREAD

**Issue by dorad007** [ReactiveKit/Bond#424]
I have installed Bond 6.2.6 with CocoaPods. While building my project, an error has appeared in the file:

`<my_proj>\Pods\Bond\Sources\Bond\Shared\NSObject+KVO.swift`
The error:
`.../NSObject+KVO.swift:239:81: Cannot convert value of type '(_, _) -> UnownedUnsafe<NSObject>' to expected argument type '(_, UnownedUnsafe<NSObject>) -> _'`
Source code:
```
deallocationDisposable.otherDisposable = object._willDeallocate.reduce(nil, {$1}).observeNext { object in
  if self.observing {
    object?.unbox.removeObserver(self, forKeyPath: self.keyPath, context: &self.context)
  }
}
```
Commenting it gave me the ability to build my project. But it's probably not the best practice...

**Comment by srdanrasic** [comment]
That's really strange that you'd get such an error. Are you using latest Xcode with the default toolchain?

**Comment by dorad007** [comment]
I have updated xcode to the latest.

בתאריך 4 ביונ' 2017 2:11 PM,‏ "Srđan Rašić" <notifications@github.com> כתב:

**Comment by dorad007** [comment]
About the toolchain, I think i haven't change it. I will try to play with
this later and will let you know.

בתאריך 4 ביונ' 2017 14:49,‏ "Dorad Levinshtein" <dorad007@gmail.com> כתב:

**Comment by srdanrasic** [comment]
Awesome! :)
