### ISSUE TITLE
Issues compiling under Xcode 9 beta 1

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveKit/Bond#425]
The Swift 4 compiler appears to have a bug that we're hitting in Bond. I've filed an issue on Swift's bug tracker, so hopefully it will be fixed in a future beta.

https://bugs.swift.org/browse/SR-5095

**Comment by srdanrasic** [comment]
I have a bad feeling about this one. Although it's something that should work, it's probably not trivial for them to implement it.

I hope I won't have to rename `Signal.Element`, that would really be a bummer.

**Comment by tonyarnold** [comment]
Honestly, I'd lean toward renaming so that we can keep projects moving under Xcode 9. It's not great, but it's pragmatic. It can always be changed back if the Swift team manage to fix the issue.

**Comment by srdanrasic** [comment]
Yeah, that's probably going to happen. I'd like to see if Swift devs have some smart suggestions first before committing to the change.

**Comment by srdanrasic** [comment]
Alternative is to drop the `Collection` conformance, but would that damage ObservableArray too much.

**Comment by tonyarnold** [comment]
I agree on both of your points. Let's see what the Swift guys say, and then you can make an informed decisions. Thanks @srdanrasic!

**Comment by fruitcoder** [comment]
Thanks so much for looking into this!

**Comment by pvegh** [comment]
A feature branch with the rename quickfix would keep us bleeding edge users floating. Using that quickfix branch with Cocoapods is easy, wouldn't have to be necessarily integrated to any future version.
Just an idea if you find the time to implement it.

**Comment by srdanrasic** [comment]
We'll have something later today - working on it :)

**Comment by srdanrasic** [comment]
Hey everyone! I created a `swift-4` branch that compiles with Xcode 9. 

In order to get it compiling I had to drop Collection protocol conformance from ObservableArray/2DArray/Dictionay/Set types. 

If you were using methods provided by Collection protocol conformance, you can still use them by calling them on the underlying collection. For example, instead of `observableArray.prefix(upTo: 3)` you should now do `observableArray.array.prefix(upTo: 3)`.

Nothing is lost from the functional perspective, it's just a bit more cumbersome to use it.

**Comment by tonyarnold** [comment]
Works for me, for now - thanks for the speedy changes @srdanrasic!

**Comment by tonyarnold** [comment]
I'm still debugging the issue, but I _think_ that this change may have broken batched moves? I can move individual elements without any problems, but the moment I try to batch a bunch of moves I get `beginUpdates` and `endUpdate` through to my tableview without any other events.

**Comment by fruitcoder** [comment]
Awesome @srdanrasic 👍

**Comment by srdanrasic** [comment]
@tonyarnold, I could not find anything related to batched changes that could be affected by this update. Maybe you are observing an issue that exists on previous versions too... Do you have any more details?

**Comment by tonyarnold** [comment]
I haven't had a chance to do much more digging, I'm sorry! 

It looks like when I `batchUpdate` moves on an `ObservableArray` to a bound `NSTableView`, that the `.reload` I would expect to see is instead coming through as `.beginUpdates` then `.endUpdates` with no actions in between. 

I'm not sure if this is Bond, or Diff - I'll need to go back and really run through it - I'll open a new issue or PR if I can figure out why this is happening.

**Comment by tonyarnold** [comment]
OK, I've had a bit of a chance to dig at this and I'm quite sure what the issue is. I've narrowed it down to the `batchUpdate` method, specifically the `.reset` code path: https://github.com/ReactiveKit/Bond/blob/master/Sources/Bond/Collections/ObservableArray.swift#L210

It looks to me like the backing array for the ObservableArray instance is never updated to include items from the proxy instance?

**Comment by srdanrasic** [comment]
@tonyarnold yeah, that seems like a bug :) We should update the array like in else block, but before we send the event. Can you see if that fixes your problem?

**Comment by tonyarnold** [comment]
It kind of fixes the issue, but I believe I have other dramas going on now (integrating with an NSOutlineView). Thanks for the confirmation.

**Comment by codedbypm** [comment]
The same issue happens when compiling with XCode 9 and Swift 3.2. Is that normal?

**Comment by srdanrasic** [comment]
These issues should now be fixed as Xcode 9 is supported since 6.3.0.
