### ISSUE TITLE
MutableObservableArray as data source in custom TableViewBond

### ISSUE THREAD

**Issue by mladenny** [ReactiveKit/Bond#428]
When creating a custom `TableViewBond` and I put the data source as `MutableObservableArray` instead of as `ObservableArray` like so:

```swift
struct MyBond: TableViewBond {
	func cellForRow(at indexPath: IndexPath, tableView: UITableView, dataSource: MutableObservableArray<NextLessonDTO>) -> UITableViewCell {
		// return cell
	}

	func titleForHeader(in section: Int, dataSource: MutableObservableArray<NextLessonDTO>) -> String? {
		// return string
	}
}
```

In my `UITableViewController` I write:

```swift
viewModel.nextLessons.bind(to: self.tableView, using: MyBond())
```

for which line Xcode is telling me `Extra argument 'using' in call`. When I command click it it shows me this:
![screen shot 2017-06-16 at 15 12 02](https://user-images.githubusercontent.com/9286345/27226141-37c50c24-52a6-11e7-8dd3-3c0bee8675a2.png)

Do you know what is the reason for it not working with `MutableObservableArray`?

**Comment by elementsrtyte** [comment]
Any updates on this? 🙏🏽

**Comment by Myryx** [comment]
Just bumped into it. @srdanrasic is there something we can do about it? It's a stopper, unfortunately :(

**Comment by srdanrasic** [comment]
Hey everyone,

I'm not sure it we can make it work for specialized table view bonds. For now the requirement is that TableViewBond has to be generic of the data source.

```swift
struct MyBond<DataSource: DataSourceProtocol>: TableViewBond {

    func cellForRow(at indexPath: IndexPath, tableView: UITableView, dataSource: DataSource) -> UITableViewCell {
       ...
    }

    func titleForHeader(in section: Int, dataSource: DataSource) -> String? {
        ...
    }
}
```


I know it's not a perfect solution, but you can always downcast the data source if needed.

```swift
struct MyBond<DataSource: DataSourceProtocol>: TableViewBond {

    func cellForRow(at indexPath: IndexPath, tableView: UITableView, dataSource: DataSource) -> UITableViewCell {
        if let dataSource = dataSource as? ObservableArray<MyObject> {
            ...
        }
    }

    func titleForHeader(in section: Int, dataSource: DataSource) -> String? {
        ...
    }
}
```

I'll see if it's possible to make non-generic table view bonds.
