### ISSUE TITLE
issue compiling xCode 9 beta - Diff library

### ISSUE THREAD

**Issue by makos88** [ReactiveKit/Bond#429]
Hello!

I added Bond library to my project. When I want to build my project I got 15 errors
![screen shot 2017-06-19 at 15 11 13](https://user-images.githubusercontent.com/3307752/27298626-b761953a-5529-11e7-8f31-246e23a722af.png)

My Podfile configuration:
![screen shot 2017-06-19 at 20 00 11](https://user-images.githubusercontent.com/3307752/27298682-ee5f243a-5529-11e7-9513-853817152023.png)

Any solutions?

**Comment by tonyarnold** [comment]
We don't properly support Xcode 9 yet - that will come closer to release. For now, you should refer to the conversation in #425.
