### ISSUE TITLE
Build fails on “Release” configuration

### ISSUE THREAD

**Issue by gilazr** [ReactiveKit/Bond#430]
I have an iOS app that's using Cocoapods. It's written in Swift 2.2, and compiled on Xcode 7.3.1. The "Bond" version is 4.3.1

On "Debug" build configuration it compiles successfully and everything's fine. On "Release" configuration I get an error:

`/Users/<APPNAME>/ios/Pods/Bond/Bond/Core/ObservableArray.swift:251:1: Type 'ObservableArray<ElementType>' does not conform to protocol 'ArrayLiteralConvertible'
`

ArrayLiteralConvertible is a swift protocol, so I don't know how or why changing the configuration affects Bond's complience with it.

**Comment by rlmartin** [comment]
This has to do with Whole Module Optimization being turned on in the Build Settings for the Bond Pod. Though this isn't necessarily recommended, you can get around this by going to Pods, choosing the Bond target, then Build Settings => Swift Compiler - Code Generation => Optimization Level => Release and changing it to `Fast [-O]` or `None [-Onone]`.

There must be some other class in a different file that the compiler is combining/optimizing with the ObservableArray class and causing this error. If you drill down on the error, is says `Multiple matching types named 'Element'` and lists two, one in this file and one that is missing. I think the key to fixing this is to identify that missing matching type and disambiguating it enough from the ObservableArray class such that the compiler doesn't optimize it and combine the two classes.

Unfortunately I don't know enough about generics in Swift to be able to resolve this right now.

**Comment by srdanrasic** [comment]
Unfortunately we cannot support older versions of Xcode.
