### ISSUE TITLE
Observable<Int> has no function `bind(to: …)`

### ISSUE THREAD

**Issue by sxmichaels** [ReactiveKit/Bond#431]
I am running into a problem with Observables and I'm not sure if it's a bug or intended behavior — the docs are not clear about it. I have four variables:

```
var observableInt: Observable<Int>
var observableStr: Observable<String>

var textView1: UITextView
var textView2: UITextView
```

For some reason, `.bind(to: …)` works in the first case below, and not the second.
```
observableStr.bind(to: textView1) // OK
observableInt.bind(to: textView2) // Error: incorrect argument label in call (have 'to:', expected 'signal:')
```

Why does this difference exist? I can't find any reference to it anywhere.

**Comment by daviskoh** [comment]
any updates?

**Comment by daviskoh** [comment]
just realized...it has to do w/ type safety and how UITextView & UITextField require `String`s

try converting the Int to a String 1st or map it like so:

```
observableInt.map({ "\($0)" }).bind(to: textView2)
```
