### ISSUE TITLE
TestFlights builds created with Xcode 9 fail processing

### ISSUE THREAD

**Issue by frankschlegel** [ReactiveKit/Bond#437]
When submitting a beta build (of an app using Bond and/or ReactiveKit) created with Xcode 9 it fails processing with the following message:

> **Invalid Bundle** - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

This is due to [this issue](https://forums.developer.apple.com/thread/81893). The "generate code coverage" option now affects all actions and not only testing. And builds that were compiled with this option are not allowed by the backend.

I expect that to be a bug and that it get's fixed in later Xcode betas, but for now you can avoid the issue by disabling code coverage generation in Bond (and all your dependencies and own targets).

**Comment by srdanrasic** [comment]
Thanks for reporting this @frankschlegel! Was it beta 3 that your tired with?

**Comment by frankschlegel** [comment]
Yes, but it actually seems to be a Carthage issue… kinda.
With Carthage the dependencies are build externally and not as part of the project build process. I guess that's why they contain coverage data now after the recent changes to Xcode.
I already filed a [bug report for Carthage](https://github.com/Carthage/Carthage/issues/2056), maybe it can be fixed there.

**Comment by srdanrasic** [comment]
Hey @frankschlegel, do you know if this is still an issue?

**Comment by frankschlegel** [comment]
Yes, it actually is. I still think it should be fixed on Carthage's side, but this seems to be harder then expected.
What you could do on your side to circumvent the issue is to disable the "Gather code coverage" option for your projects if you don't need it.

**Comment by srdanrasic** [comment]
Damn :) Do you mean like app projects, or we need to disable it in the frameworks?

**Comment by frankschlegel** [comment]
In the frameworks -.-

Background: The binaries get build with coverage data baked in when you enable that option and use the "build" action, but not on "archive". So it's usually not an issue if you build the frameworks alongside your app, like you would do when using submodules or CocoaPods. However, Carthage builds the frameworks independently by using the "build" action and you just copy them to your app when deploying… so that the coverage-induced binary ends up in you final app bundle.

**Comment by SeanRobinson159** [comment]
I'm having the same issue.
Xcode 9, Swift 4, and Carthage.

**Comment by frankschlegel** [comment]
@SeanRobinson159 Yes, there was a big discussion going on in the linked Carthage issue. I think they fixed it now (using the `archive` instead of the `build` action for ARM binaries), but it's not yet released.

**Comment by srdanrasic** [comment]
This is now fixed by Carthage. I'm closing the issue.
