### ISSUE TITLE
ComputedObservable

### ISSUE THREAD

**Issue by dorad007** [ReactiveKit/Bond#439]
Could you please add (here or in ReactiveKit) a ComputedObservable class like in [knockoutjs](http://knockoutjs.com/documentation/computedObservables.html)? it's is very useful (maybe there is a better option here, but i haven't found one)

**Comment by srdanrasic** [comment]
Hey @dorad007! 

There for the suggestion, however there are already few ways to achieve this so I don't think we need a special type for it. Here is what one could do:

```swift

class C {

    let firstName: Observable<String>
    let lastName: Observable<String>

    var fullName: SafeSignal<String> {
        return firstName.combineLatest(with: lastName) { $0 + " " + $1 }
    }
}
```

Check out ReactiveKit [README](https://github.com/ReactiveKit/ReactiveKit) for more info. Bond is built on top of ReactiveKit.

Hope this helps!

**Comment by dorad007** [comment]
You might chose a specific use case of computed observable and demonstrated the implementation. However, ComputedObservable is a wider component.
Additionally, i think that the implementation is really not intuitive. Anyway thanks.
