### ISSUE TITLE
Issue when upgrading to Swift 3, Bond 6.2.8

### ISSUE THREAD

**Issue by DarkByte** [ReactiveKit/Bond#443]
I'm upgrading from Swift 2.3 to 3.0 (Xcode 8.2.1), so I've updated the podfile (to no longer restrict the versions). This way my project now uses the 6.2.8 version of Bond, but fails to compile as seen in the attached screenshot.

Any ideas on how to fix this? Thanks in advance!

![screen shot 2017-07-31 at 16 31 39](https://user-images.githubusercontent.com/345800/28780070-2866eda2-760e-11e7-905d-f82be7caa1b7.png)

**Comment by limeytrader007** [comment]
Any luck on this? I'm facing a similar issue that I put on the 'Issues' tab when upgrading to XCode 9.

**Comment by DarkByte** [comment]
No luck so far, as I was busy switching between branches for preparing a release build (using the old Swift 2.3 code). If I find something, I'll be sure to post it here - please do the same :)

**Comment by limeytrader007** [comment]
Check my post (it's the one above yours in the Issues tab). Developer is saying to switch to swift-4 branch but I'm unsure how to add Bonds to my project since I did it with CocoaPods.

**Comment by limeytrader007** [comment]
Hey DarkByte. Check my post again, owner responded. Thanks!

**Comment by DarkByte3PG** [comment]
Thanks, @limeytrader007 , I'll try that.

**Comment by DarkByte3PG** [comment]
@limeytrader007 @srdanrasic : I'm still having a problem with using the swift-4 branch, as illustrated in the attached screenshot.

Just a reminder: I am using Xcode 8.2.1 (working on converting the project to Swift 3).

![screen shot 2017-08-04 at 10 16 03](https://user-images.githubusercontent.com/16716552/28958327-98a8e244-78fe-11e7-86b0-58e9b2b39871.png)

**Comment by limeytrader007** [comment]
Similar issue.. looking into it now...

![screen shot 2017-08-04 at 8 41 28 am 3](https://user-images.githubusercontent.com/21250561/28969227-af5a302c-78f1-11e7-9ae6-a713ae6df615.png)

**Comment by DarkByte3PG** [comment]
bnd_text? I think you should replace that with "reactive.text", since Bond v6.

**Comment by limeytrader007** [comment]
yeah I think you're right. Do you have a link to that page? I remember hearing about it but can't find it. Thanks!

**Comment by DarkByte3PG** [comment]
You can find this on the main page of Bond (readme.md)

![screen shot 2017-08-04 at 16 09 05](https://user-images.githubusercontent.com/16716552/28969950-4d455a54-792f-11e7-8475-dbb653c51c4e.png)

**Comment by limeytrader007** [comment]
Lemme try it. Thanks boss!

**Comment by DarkByte3PG** [comment]
Reminder:

@limeytrader007 @srdanrasic : I'm still having a problem with using the swift-4 branch, as illustrated in the attached screenshot - using Xcode 8.2.1 (working on converting the project to Swift 3).

![screen shot 2017-08-04 at 10 16 03](https://user-images.githubusercontent.com/16716552/28958327-98a8e244-78fe-11e7-86b0-58e9b2b39871.png)

**Comment by srdanrasic** [comment]
@DarkByte3PG, how are you compiling Bond?

**Comment by DarkByte3PG** [comment]
I'm integrating it via cocoapods, if that's what you mean.
