### ISSUE TITLE
Upgraded to XCode 9 Beta 4 - Compilation Error

### ISSUE THREAD

**Issue by limeytrader007** [ReactiveKit/Bond#444]
Hey all,

I upgraded my project to XCode 9, Beta 4 and Bond will not compile now.
I did a fresh pod install but I get 6 or 7 of these:

Type 'Observable2DArray<SectionMetadata, Item>' does not conform to protocol 'SignalProtocol'

Any ideas?

Thanks

**Comment by srdanrasic** [comment]
There are issues with Swift 4 compatibility. Please use `swift-4` branch.

Here is more info: https://github.com/ReactiveKit/Bond/issues/425

**Comment by limeytrader007** [comment]
How do I install from your Swift 4 branch if Bond was initially installed with Cocoapods a few months back? Thanks!

**Comment by srdanrasic** [comment]
It's in CocoaPods guide :)
https://guides.cocoapods.org/using/the-podfile.html

```
pod 'Bond', :git => 'https://github.com/ReactiveKit/Bond.git', :branch => 'swift-4'
```

**Comment by limeytrader007** [comment]
You ROCK!!! Thank you so much sir!

**Comment by limeytrader007** [comment]
@srdanrasic Now having this sir...

![screen shot 2017-08-04 at 8 41 28 am 3](https://user-images.githubusercontent.com/21250561/28969628-51c9731c-78f3-11e7-83da-3f0a27382ea2.png)

**Comment by srdanrasic** [comment]
Hey @limeytrader007 - it seems that you are upgrading the an older version. Please check out the migration guide: https://github.com/ReactiveKit/Bond#migration
