### ISSUE TITLE
Index Out of Range using first(where: { }) and filter({ }) on MutableObservable2DArray

### ISSUE THREAD

**Issue by SeanRobinson159** [ReactiveKit/Bond#445]
I have the following class setup:
```
class Session {
    private var items: MutableObservable2DArray<String, Item>
    var isUploading: Bool { return items.first(where: { $0.isUploading }) != nil }
   ...
}
```

```
class Item {
    var isUploading: Bool
    ...
}
```
When I try to access `session.isUploading` I get an index out of range error. I tried switching it to use a filter, like this:

`var isUploading: Bool { return !items.filter({ $0.isUploading }).isEmpty }`

I still get `fatal error: Index out of range`

Is this a bug? Or is it not an intended use of the `ObservableArray`

**Comment by srdanrasic** [comment]
That's a bug! Thanks for reporting it, I'm looking into it.

**Comment by marclove** [comment]
I'm encountering the same problem with `index(of:)`, though I suspect it's the same root cause: attempting to iterate over elements in sections using subscripts, starting with an index of 0, without first checking if the section is empty.

**Comment by srdanrasic** [comment]
This bug has been fixed in one of the previous releases. Sorry for the late notification.
