### ISSUE TITLE
Section header view

### ISSUE THREAD

**Issue by Maxatma** [ReactiveKit/Bond#446]
I'm using 2d sections, bind to array, using table bond. But I only can set tittle for section, however I need change color, add image, etc. 
how to do that?

**Comment by srdanrasic** [comment]
Hey man!

In your case you'll need to implement your own delegate methods to provide custom views for headers/footers. You can use [Reactive Delegates](https://github.com/ReactiveKit/Bond#reactive-delegates) to implement `tableView:viewForHeaderInSection:` method if you want to keep bindings.

**Comment by Maxatma** [comment]
Any example? Example's `selectedRow` method and feed to `numberOfRowsInSection ` isn't so clearly to understand how to bind uiviews to `tableView:viewForHeaderInSection:` method.
Should I have Propery<Array<UIView>> and feed them into it?

**Comment by dcrobert** [comment]
Depending on the use case, you could add section metadata for the sections and then load a custom view based on that metadata.

**Comment by Maxatma** [comment]
@dcrobert  so how to do that ?

**Comment by Maxatma** [comment]
@dcrobert thanks, for example. But, I guess this is nothing about reactive delegates, mentioned by @srdanrasic.
