### ISSUE TITLE
Memory leak in ProtocolProxy.swift function arg

### ISSUE THREAD

**Issue by debbiegoldsmith** [ReactiveKit/Bond#447]
The argument extractor function arg allocates memory to an UnsafeMutablePointer, but never deallocates it before returning. This causes a leak. The fix is to extract the pointee, deallocate the memory, then return the pointee.

**Comment by debbiegoldsmith** [comment]
Patch attached.
[LeakFix.diff.txt](https://github.com/ReactiveKit/Bond/files/1198835/LeakFix.diff.txt)

**Comment by srdanrasic** [comment]
Thanks, I've applied the fix! :)
