### ISSUE TITLE
Ambiguous reference to member `text`

### ISSUE THREAD

**Issue by prakashraman** [ReactiveKit/Bond#450]
HI

I have a ViewModel
`
class ViewModel {
    var name = Observable("Prakash Raman")
}
`

and a textfield

`
var nameTextField = UITextField()
`

I would like to bidirectionalBind the two. Although then I add the line of code

`
viewModel.name.bidirectionalBind(to: nameTextField.reactive.text)
`
I get the errror

**Ambiguous reference to member `text`**

**Comment by prakashraman** [comment]
Also. A one way binding works fine.

`
viewModel.name.bind(to: nameTextField)
`

**Comment by srdanrasic** [comment]
You are trying to bidirectionally bind `Observable<String>` with `Observable<String?>`. Bidirectional binding only works with the same types.

**Comment by prakashraman** [comment]
Ah! Damn, right! What a simple change. Yes it working great now :) 

Thanks!

**Comment by jeetdholakia** [comment]
Hi, I am new to the overall Rx world and could not understand the solution clearly. Can you please explain what the simple change was? It would be helpful.

Thanks!
