### ISSUE TITLE
Xcode 9 beta 5 build failed error

### ISSUE THREAD

**Issue by sathishkraj** [ReactiveKit/Bond#453]
Xcode 9 beta 5, swift 3.2 with carthage version 0.23.0, currently using "SwiftBond/Bond" "6.2.6" build failed on carthage update and tried "ReactiveKit/Bond" "v5.4.6" but got same error. Am i missing anything?

**Comment by sathishkraj** [comment]
got it, confused with swift 4 complier. using "develop" solved it

**Comment by sathishkraj** [comment]
but "SwiftBond/Bond" "6.2.6"  should compile in xcode 9 right. will there be any fix for this error? Build Failed Task failed with exit code 65:, This usually indicates that project itself failed to compile.

**Comment by srdanrasic** [comment]
Unfortunately Xcode 9 cannot compile Bond 6.2.6 due to breaking changes in Swift (in compatibility mode too). Only way to use Bond with Xcode 9 at the moment is to switch to `swift-4` branch. 

Of course, as soon as Xcode 9 is out of beta, there will be Bond release supporting it.
