### ISSUE TITLE
Bond Podspec points to ReactiveKit with a critical issue

### ISSUE THREAD

**Issue by Cedrick84** [ReactiveKit/Bond#454]
I posted [this](https://github.com/ReactiveKit/ReactiveKit/issues/153) issue in the ReactiveKit section, which was fixed some days ago by @srdanrasic. Now because my project also heavily relies on Bond (thanks for all the great work guys) I can not easily use the fixed version. Can you please change the dependency from 3.5.3 to 3.6.0? Many thanks

**Comment by Cedrick84** [comment]
Created [a pull request](https://github.com/ReactiveKit/Bond/pull/455)

**Comment by srdanrasic** [comment]
`~> 3.5.3` only specifies minimal required version. `pod update` should install the latest compatible version which is 3.6.0. Hmmmmm.... :)

Anyway, thanks for the PR, let's try it that way. I'm pushing it to CocoaPods now.
