### ISSUE TITLE
What's the preferred way of accessing the parent/owner of an observed property?

### ISSUE THREAD

**Issue by mwhrtin** [ReactiveKit/Bond#456]
I'm new to ReactiveKit and Bond, so perhaps there is an obvious answer.  What's the recommended way when accessing the parent/owner of the property I'm observing?

Let say I have the object `myObject` with an observable boolean property `someProperty`. When the boolean changes I want access to `myObject`, the parent of the property I'm observing.

Is this the preferred way:

```swift
myObject.someProperty.bind(to: self) { [weak myObject, someOtherObject] me, value in
    // do stuff to me, value and a weak myObject reference here
    me.callSomeMethod(myObject, someOtherObject)
}
```

**Comment by srdanrasic** [comment]
There is no "official" way of doing something like that so what you are doing is not bad :)
