### ISSUE TITLE
How to bind a Obersavable to a button state

### ISSUE THREAD

**Issue by prakashraman** [ReactiveKit/Bond#457]
I would like to know how to bind a "Observable" to a state of the a Button. I have a ViewModel class as such 

```
class ViewController : UIViewController {
    var button : UIButton()
}

class ViewModel {
    var selectionType : Observable<String?> = Observable(nil)
}

```

Use Case:
When the "selectionType" string observable is set to "checked" I would like to **enable** the button. And when it is to "unchecked" I would like to **disable** the button

**Comment by Vinzius** [comment]
Hi,

You should `.map` the value of your `.selectionType` property to a Bool. Something like
`.selectionType.map { $0 == "checked" }`
And then bind the result to the `reactive.isEnabled` of your button.
`.bind(self.button.reactive.isEnabled)`
That should work.

For some "support", you better should use the gitter ( https://gitter.im/ReactiveKit/General )

Bests
