### ISSUE TITLE
How to combine an array of Observables

### ISSUE THREAD

**Issue by chrisjb82** [ReactiveKit/Bond#458]
Hi there

I am trying to combine an array of Observables and bind it to a single Observable. The number of Observables is not know at compile time.

`
    let isDataValid = Observable<Bool>(false)
    
    var questionViews:[KnowledgeQuestionView]! {
        didSet {
            var observables = [Observable<Bool>]()
            
            for questionView in questionViews {
                observables.append(questionView.isDataValid)
            }
            
            combineLatest(observables, combine: {elements -> Bool in
                /*
                 iterate over elements and if any are false 'return false'
                 */
                
                return true
            }).bind(to: isDataValid)
        }
    }
`

The issue i am having is that the combineLatest method which takes an array only takes an array of Signals, not SignalProtocol elements, therefore the code above fails to combine as it can't convert `Property<Bool>` to `Signal<_,_>`

Is there any way to achieve what i want using ReactiveKit?

Many thanks

Chris

**Comment by srdanrasic** [comment]
Unfortunately there is no such operator at this time.

**Comment by tkanzakic** [comment]
Not sure if this will work for you but in a similar case I do something like this and it works like a charm:

```Swift
let isDataValid = Observable(false)

var questionViews:[KnowledgeQuestionView]! {
    didSet {
        let observables = questionViews.map {
            $0.isDataValid.toSignal()
        }
        
        combineLatest(observables) { elements -> Bool in
            /*
             iterate over elements and if any are false 'return false'
             */
            
            return true
        }).bind(to: isDataValid)
    }
}
```
