### ISSUE TITLE
Bond 6 operators has problem because Bond and ReactiveKit use the same operator.

### ISSUE THREAD

**Issue by minsOne** [ReactiveKit/Bond#459]
Hello. I was using Bond 5 and migrating Bond 6, but there was a problem.

```
let listSignal = Signal1<[[Int]]>.just([])
let filteredListSignal = listSignal.filter { $0.count == 2 }.eraseType()
```

In the above code, I want to use filter operator of ReactiveKit and allow only 2 arrays. But the return type of filter operator is ObservableArrayEvent<[Int]>.

This Problem is that the compiler points to Bond filter operator.

The operators that can cause this problem are map, filter operator. Because ReactiveKit uses same function and uses it.

So I want map, filter operator names like ReactiveKit not to overlap.

Thanks.

**Comment by srdanrasic** [comment]
Hey @minsOne,

The operators are implemented only in ReactiveKit. Bond does not provide operators. 

I tested your code and it works fine in my project importing both ReactiveKit and Bond.

Xcode can sometimes point to the wrong implementation when you Command-Click the method, but that does not mean the compile is using it.

**Comment by minsOne** [comment]
Thanks for the reply @srdanrasic 

you says 'The operators are implemented only in ReactiveKit. Bond does not provide operators.', but Bond`s map, filter operator is existed. [Here](https://github.com/ReactiveKit/Bond/blob/master/Sources/Bond/Collections/ObservableArray.swift#L394)

The problem I'm experiencing is when I used a two-dimensional array type.

Because array type is conforming ObservableArrayEventProtocol, then operator such as map, filter on Bond can use.

So Instead of renaming an existing operator, i`d like to modify the code in the [DataSource.swift](https://github.com/ReactiveKit/Bond/blob/master/Sources/Bond/DataSource.swift#L92) file as follows:

```
extension Array: DataSourceEventProtocol, ObservableArrayEventProtocol {
—
extension Array: DataSourceEventProtocol {
```

Then, compiler point only Reactivekit when I used two-dimensional array type.

Thanks

**Comment by srdanrasic** [comment]
Ah, you are right about that when arrays are in question. Unfortunately, we cannot just drop `ObservableArrayEventProtocol` as some other things would stop working.

What you can do is be explicit about the closure types so the compiler knows which operator to use. Instead of:

```swift
listSignal.filter { $0.count == 2 }.eraseType()
```

Do:

```swift
listSignal.filter { (element: Int) -> Bool in
    return element.count == 2
}.eraseType()
```

Hope this helps.

**Comment by minsOne** [comment]
Thanks.
