### ISSUE TITLE
Cannot build with Xcode 9 and Swift 4

### ISSUE THREAD

**Issue by AndreaStevanato** [ReactiveKit/Bond#460]
I tried the pod version `6.3.0` on a new project with Xcode 9 GM and I have the following compile errors related to `Diff`.

![screen shot 2017-09-13 at 16 21 00](https://user-images.githubusercontent.com/15797080/30382509-97451024-989f-11e7-90ae-5ed50bcdf626.png)

**Comment by srdanrasic** [comment]
Looks like CocoaPods is trying to compile it using Swift 4. Can you try adding this to your podfile?
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Diff'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```

**Comment by andr3a88** [comment]
I had to put both `Diff` and `Bond` to make it compile

`````
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Diff' || target.name == 'Bond'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
``````

**Comment by srdanrasic** [comment]
Great, thanks for the feedback :)

This is a limitation of CocoaPods. I'm not sure if there is a way to tell it what Swift version should the compiler use. Here is the official thread on the issue: https://github.com/CocoaPods/CocoaPods/issues/6791

In general, I'd recommend using Carthage as it honours project settings, among other things.

**Comment by mecid** [comment]
Not working for me, same error in Diff appearing.

**Comment by tonyarnold** [comment]
@mecid as @srdanrasic mentioned above, this is a limitation of CocoaPods and we'd recommend you look at using Carthage instead.

I'm working on a Swift 4 version of Diff, but I'm not sure that really solves the problem as I don't believe that Bond is ready to move to Swift 4 syntax.

**Comment by mecid** [comment]
@tonyarnold  there is a problem with Diff and Swift 4, no problem with CocoaPods. Please release new Diff version with Swift 4.

**Comment by srdanrasic** [comment]
@mecid  It's true that Diff and Bond are not written using Swift 4 syntax (yet), but Swift 4 compiler can use code written in Swift 3.2 syntax without problems. It's CocoaPods that does not recognise the syntax version nor allow us to specify it manually.

Integration with Carthage or manually works flawless.

**Comment by mecid** [comment]
@srdanrasic as you can see on screenshot, problem is using removed in Swift4 toIntMax() function.

**Comment by srdanrasic** [comment]
The script in podfile is no longer necessary as of 6.4.

**Comment by w4-sglim** [comment]
Hey guys! I found solution! Remove the lines like below in your **Podfile**:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

This enforce your library to use swift 3.0.

With this solution, bond (>= 6.4) works with Swift 4.x.
