### ISSUE TITLE
Pod installs version 6.2.1 instead of 6.3.0

### ISSUE THREAD

**Issue by KausiAhmed** [ReactiveKit/Bond#461]
Pod file has the following line:
`pod 'Bond'`

When I run `pod install` I get version `6.2.11`.

Analyzing dependencies
Downloading dependencies
Using Bolts (1.8.4)
Using Bond (6.2.11)
Generating Pods project
Removing static analyzer support
Integrating client project
Sending stats
Pod installation complete! There are 15 dependencies from the Podfile and 24 total pods installed.

**Comment by srdanrasic** [comment]
This is a known CocoaPods issues. Try running `pod repo update` and then they updating the dependencies again.

**Comment by KausiAhmed** [comment]
Yep.  Just fixed it.  Thanks.
