### ISSUE TITLE
Problem with EventProducer - Migration from v4.x to v5.x

### ISSUE THREAD

**Issue by lucasPelizza** [ReactiveKit/Bond#462]
I am migrating my code from Bond 4 to Bond 5 but I am having a problem with replacing this line:

```swift
let user: EventProducer < Int > = EventProducer (replayLength: 1)
```

I was wondering if any of you could help me with this migration.

**Comment by tonyarnold** [comment]
Hi @lucasPelizza, I _think_ you want to change that to:

```swift
let user = ReplayOneSubject<Int, NoError>()
```
