### ISSUE TITLE
Problem with the replacement of "bnd_" with "reactive"

### ISSUE THREAD

**Issue by lucasPelizza** [ReactiveKit/Bond#464]
On the documents says:

> ## Migration from v5.x to v6.x
>Extensions are moved into reactive proxy. Replace occurrences of bnd_ with reactive.. For example `label.bnd_text` becomes `label.reactive.text`. The simplest way is to do Search and Replace in Xcode across the project.

On my code in many parts of them I have this:
```swift
openButton.bnd_highlighted.value = newValue;
```
and
```swift
self.bnd_highlighted.observe { ... }
```

when I changed this line following the documentation, it looks like:
```swift
self.reactive.isHighlighted.value = newValue
```
and
```swift
self.reactive.isHighlighted.observeNext { ... }
```

But the problem is that it does not compile with these changes.

**Comment by srdanrasic** [comment]
Yeah, there have been many changes... Type `Bond` is used as a binding point for signals and observables. It does not have `.value` property as it is pointless because you can just do `self.isHighlighted = ...`.

**Comment by lucasPelizza** [comment]
@srdanrasic, 
First of all, thank you for taking the time to answer my question.

I will try with that solution, but what do you think about the second line:
"self.bnd_highlighted.observe" 
Because the reactive.isHighlighted does not have the observeNext

**Comment by Maxatma** [comment]
@lucasPelizza 
 Bond<Bool> isn't a Signal or a Producer. So u can't observe it. But u can bind to it. 
Something like that: 
vc has a button:
`    @IBOutlet weak var button: UIButton!`
vm has Observable:
`    let highlighted                 = Observable<Bool>(true)
`
` vm.highlighted.bind(to: button.reactive.isHighlighted)
`
so if u need change ur button highlights u do in vm: 
`highlighted.next(false)`

I'm not sure about previous versions, was a button.isHighlighted available to observe?
