### ISSUE TITLE
Published subject warning at XCode 9

### ISSUE THREAD

**Issue by beltik** [ReactiveKit/Bond#468]
Hi,

I have following in header of my class:
    var publishSubject = PublishSubject<Bool, NoError>()

When i update to XCode 9 and move to Carthage everything is ok, but its like warning - Use of unresolving identifier 'PublishSubject'

**Comment by srdanrasic** [comment]
Hey, did you `import ReactiveKit`?

**Comment by beltik** [comment]
I have not. Thanks, it solve problem. However, in XCode 8 i did not import it and everything was just fine.

**Comment by srdanrasic** [comment]
Yeah, I've been bumping to those things too. Sometimes you can use something you don't import. But I'd say that was a bug in Xcode.
