### ISSUE TITLE
Trying binding text field reactive text to Observable failed

### ISSUE THREAD

**Issue by beltik** [ReactiveKit/Bond#470]
Hi,

I trying to do:

txtf.reactive.text
 .map { $0!.isEmpty }
.bind(to: self.vm.enteredLoginTxt)

But it's not work, xcode complain: Missing argument for parameter 'setter' in call.
How to fix it? I simply want to bind text field text to Observable(String)

**Comment by beltik** [comment]
Also look like :         self.vm.enteredLoginTxt.bind(to: txtf.reactive.text) not working.
Or maybe it's my mistake in code somewhere else?

**Comment by srdanrasic** [comment]
`UITextField.text` is of `String?` type, not `String` :)

**Comment by beltik** [comment]
it appears that i did add [input mask lib](https://github.com/RedMadRobot/input-mask-ios) and text field stop to send events when value changed.
