### ISSUE TITLE
Binding two observables has no effect

### ISSUE THREAD

**Issue by beltik** [ReactiveKit/Bond#471]
Hi.

I tried to bind Observable(String) to another Observable(String). I did : 
loginEnteredText.bind(to: enterItem.enteredLoginTxt). 
However, when enteredLoginTxt changes, loginEnteredText has not change :(

Following code work, but i rather want to bind :)

 enterItem.enteredLoginTxt.observeNext { (x) in
            self.loginEnteredText.value = x
        }

**Comment by srdanrasic** [comment]
It's because you bound `loginEnteredText` to `enteredLoginTxt`. Either reverse the order or use bidirectional bindings. Please consult readme for more info.
