### ISSUE TITLE
Pod does not compile: Value of optional type 'Selector?' not unwrapped in file "NSObject+KVO.swift"

### ISSUE THREAD

**Issue by tadasz** [ReactiveKit/Bond#479]
Xcode 9.0
Bond (6.4.2)

/Pods/Bond/Sources/Bond/Shared/NSObject+KVO.swift:335:47: Value of optional type 'Selector?' not unwrapped; did you mean to use '!' or '?'?

line that is breaking:
`unsafeBitCast(imp, to: _IMP.self)(me, selector)`

**Comment by caprapaditu** [comment]
Same problem

**Comment by Janneman84** [comment]
Here too in 6.4.0, I'm back to 6.3.0 for now.

**Comment by srdanrasic** [comment]
Can you try 6.4.3? Thanks :)

**Comment by pkl728** [comment]
To fix this I had to go into my project and manually set my Bond pod to use Swift 4.0. When I did that it started working.

**Comment by tadasz** [comment]
it's still the same

**Comment by srdanrasic** [comment]
@tadasz thanks for checking it out. Is your project written in Swift 4?

**Comment by tadasz** [comment]
yes it is. once i force selector `unsafeBitCast(imp, to: _IMP.self)(me, selector!)`  it compiles fine

**Comment by Janneman84** [comment]
Doesn't help here either, I'm trying to run my current Swift 3 project in Xcode 9.

**Comment by srdanrasic** [comment]
It's not a code problem. The project compiles without any warning with Carthage or as standalone. It's the CocoaPods integrations that is messing things up and I'm not yet sure where the problem is.

**Comment by grzegorzkrukowski** [comment]
Try adding this in your pod file:

`post_install do |installer|
    installer.pods_project.targets.each do |target|
        if
            target.name == ‘Bond’
            target.build_configurations.each do |config|
                config.build_settings[‘SWIFT_VERSION’] = ‘4.0’
            end
        end
    end
end`

**Comment by srdanrasic** [comment]
This should be working now without any scripts.

**Comment by bj97301** [comment]
Got this error just now with version 6.6.0 swift 3 xcode 9.2.

**Comment by bj97301** [comment]
Went back to 6.3.0 and seems to work but it would be nice to use the latest version.

**Comment by gabrielsscavalcante** [comment]
I had the same issue right now...

**Comment by srdanrasic** [comment]
What version of CocoaPods do you use? Bond does not support Swift 3 anymore.

**Comment by mikestalker** [comment]
I use cocoapods-1.4.0
Set everywhere Swift 4.0
The same problem.

**Comment by w4-sglim** [comment]
Hey guys! I found solution! Remove the lines like below:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

This enforce your library to use swift 3.0.
