### ISSUE TITLE
Initial values for bound controls?

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveKit/Bond#480]
This seems like it should have a simple answer that I'm missing. Right now, I find myself having to follow this sequence to ensure my control's initial states are correct:

1. Manually set the value of the control
2. Bind the control to the Observable/Property on my view model

If I don't do step 1, my control's initial value is not seeded correctly. I obviously can't use `start(with: …)` in the context of a DynamicSubject/bidirectionalMap (as it's then converted to a Signal). 

```swift
myControl.reactive.myProperty.bind(to: viewModel.backingProperty)
```

I would have assumed that calling `bind(to: …)` would propagate the value of  `viewModel.backingProperty` to `myControl.reactive.myProperty`? Am I doing something silly here?

**Comment by tonyarnold** [comment]
No, now I get that this isn't implemented. 

I guess it's probably a two-stage change to support something like this:

```swift
import ReactiveKit

extension SignalProtocol where Error == NoError {

    /// Establish a one-way binding between the source and the bindable.
    /// - Parameter bindable: A binding target that will receive signal events.
    /// - Returns: A disposable that can cancel the binding.
    @discardableResult
    public func bind<B: BindableProtocol>(to bindable: B, startingWith element: B.Element) -> Disposable where B.Element == Element {
        return bindable.bind(signal: toSignal().start(with: element))
    }

    /// Establish a one-way binding between the source and the bindable.
    /// - Parameter bindable: A binding target that will receive signal events.
    /// - Returns: A disposable that can cancel the binding.
    @discardableResult
    public func bind<B: BindableProtocol>(to bindable: B, startingWith element: B.Element) -> Disposable where B.Element: OptionalProtocol, B.Element.Wrapped == Element {
        return map { B.Element($0) }.bind(to: bindable, startingWith: element)
    }
}

extension BindableProtocol where Self: SignalProtocol, Self.Error == NoError {

    /// Establish a two-way binding between the source and the bindable.
    /// - Parameter target: A binding target that will receive events from
    ///     the receiver and a source that will send events to the receiver.
    /// - Returns: A disposable that can cancel the binding.
    @discardableResult
    public func bidirectionalBind<B: BindableProtocol & SignalProtocol>(to target: B, startingWith element: B.Element) -> Disposable where B.Element == Element, B.Error == Error {
        let context: ExecutionContext = .nonRecursive()
        let d1 = observeIn(context).bind(to: target, startingWith: element)
        let d2 = target.observeIn(context).bind(to: self)
        return CompositeDisposable([d1, d2])
    }
}
```

And then some kind of extension to support providing the `startingWith:` value from a `DynamicSubject` or `Property` instance.

**Comment by tonyarnold** [comment]
Nah, that doesn't work at all. 

A `bidirectionalMap(…).bidirectionalBind(…)` seems to send the control's value first to update the view model's property which is the opposite of what I'd want. 

I think this might be the result of `bidirectionalBind(…)` mapping in the opposite direction of what I'd expect. For example, I would expect the following to be an expression of me binding the value of my control to the view model _first_, then binding the view model back to the control. 

```swift
myControl.reactive.someProperty.bidirectionalBind(to: viewModel.property)
```

Is my thinking off base here? I can't go in the other direction, because I'm using `bidirectionalMap(…)`.

**Comment by srdanrasic** [comment]
You are right, you can't use `start(with:)` because the control will immediately follow with it's value and it does not work with bidirectional binding.

Solving bidirectional binding's initial value is actually quite easy. Since both sides must be subjects, you can just reverse the order.

```swift
viewModel.property.bidirectionalBind(to: myControl.reactive.someProperty)
```

Both one- and bi-directional bindings start with the value on the left hand side.

Solving one-directional binding is not trivial as right hand side can be anything conforming to `BindableProtocol` - meaning it might not even have a value to use (eg not be a `Property`).

Something along your extensions could be the answer. You can suppress control's initial value by applying  `skip(1)` before `start(with:)`. Unfortunately `1` is a guess here that will work in 99% of cases, but could burn you in the remaining 1%. If we had an operator that skips all synchronous events, it would be a better choice, but probably sill not perfect.

If your controls are usually represented by DynamicSubjects, you could extend DynamicSubjects and provide `bind(to:startingWith)` method where you do something like:  

```swift
extension DynamicSubject {

    @discardableResult
    public func bind<B: BindableProtocol>(to bindable: B, startingWith element: B.Element) -> Disposable where B.Element == Element {
        Signal.just(element).bind(to: self) // set initial value
        return bind(to: bindable)
    }
}
```

If they are not subjects, maybe just stick with the manual setting of initial value. I can't think of a better idea at the moment :)

**Comment by tonyarnold** [comment]
`bidirectionalBinding(…)` is fine, it's the `bidirectionalMap(…)` that's causing me grief. I can't invert the order when using that.

**Comment by srdanrasic** [comment]
Ah, right, because `bidirectionalMap` is implemented on `DynamicSubject`. I think this could be moved, or re-implemented, on SubjectProtocol so Property gets it too.

**Comment by tonyarnold** [comment]
That's what I was hoping. I'm having a (very uneducated) look right now :)

**Comment by srdanrasic** [comment]
Ok, but don't spend to much time on it. I'll have time later today to look into it too.

**Comment by tonyarnold** [comment]
Hey, perfect! If you're happy to have a look, that would be great - thanks! I'll leave it be.

**Comment by srdanrasic** [comment]
I've added `bidirectionalMap` to `Property` in 6.4.3 :)

**Comment by tonyarnold** [comment]
Works _beautifully_! Thank you, @srdanrasic!
