### ISSUE TITLE
observeNext() killed by authorization requests (like in CLLocationManager and PHPhotoLibrary)

### ISSUE THREAD

**Issue by Janneman84** [ReactiveKit/Bond#487]
When using locations or photos you need to ask the user for permission, like this:
`locationManager.requestWhenInUseAuthorization()`

When you run the app for the first time this will show you a dialog. Before this I set an observer in a photos array like this:
```
_ = self.project.photos.observeNext(with: {[weak self] item in
	let count = item?.count ?? 0
	print("photo count: \(count)")
})
```

This works fine, until an authorization dialog like above has been shown. The observer just stops working then, which is most peculiar. You can test this with photos too:

```
PHPhotoLibrary.requestAuthorization({(status:PHAuthorizationStatus)in
	switch status {
	case .denied:
		break
	case .authorized:
		break
	default:
		break
	}
})
```

The only real relation between the authorization request and the observer is that they're in the same ViewController.

You'll need to completely remove the app from the device every time you test. Can anyone give this a try?

I'm on iOS 11/Xcode 9/Swift 4/Bond 6.5.0

**Comment by Janneman84** [comment]
Okay I found out that it has to do with the `UISplitViewController` that I'm using. If I run the app on iPhone it works fine but when I run it on iPad in split view mode it does not. I have an other app that doesn't use `UISplitViewController` and there it works fine on iPad as well.

I'll see if there is a difference between master and detail, I've only tried detail so far.

**Comment by srdanrasic** [comment]
This does not seem like a Bond issue. I hope you have figured it out.
