### ISSUE TITLE
Memory leak with UITableView binding

### ISSUE THREAD

**Issue by XavierQuincieux** [ReactiveKit/Bond#489]
Hi,

i did a binding between an ObservableArray and a UITableView: 

```swift
myArray.bind(to: tableView) {
   (array, tableView, indexPath) in

    return tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
}
```

but when I leave my view controller, the table view is deinit as it should be, but the cells are kept in memory. I don't observe this behavior when implementing UITableViewDelegate/DataSource and observing myArray to manually apply changes using Event<ObservableArray<XXX>, NoError>.

**Comment by srdanrasic** [comment]
Hi @XavierQuincieux,

Can you check what version you are using? There have been some fixes around that recently, but v6.5.2 should be good to go. I just run some additional tests and my cells are properly deallocating.
