### ISSUE TITLE
Use of unresolved identifier 'combineLatest'

### ISSUE THREAD

**Issue by omerozk** [ReactiveKit/Bond#490]
Hi guys,

I'm trying to use the combineLatest in a test project.
But i get the error `Use of unresolved identifier 'combineLatest` but i can't figure out what i'm missing. I don't find other example of this implementation.

I'm using the latest version 6.5.2 with swift 4 and iOS target 10+

Code:

```
import Bond

    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var loginButton: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()

// this work
        _ = emailTextField.reactive.text.observeNext { text in
            print(text!)
        }
        
// this show Use of unresolved identifier 'combineLatest
        combineLatest(emailTextField.reactive.text, passwordTextField.reactive.text) { email, pass in
            return email.length > 0 && pass.length > 0
            }
            .bind(to: loginButton.reactive.enabled)
    }
```

Do you have any idea?

**Comment by dcrobert** [comment]
import ReactiveKit

**Comment by omerozk** [comment]
Thanks i tried with it also but then i got a new errors.

In the first line i get:  Argument type '(_, _) -> Bool' does not conform to expected type 'SignalProtocol'

```
combineLatest(emailTextField.reactive.text, passwordTextField.reactive.text) { email, pass in
     return email.length > 0 && pass.length > 0
}.bind(to: loginButton.reactive.isEnabled)

```

Now what i did to bypass this error is to don't use the parameter.

```
combineLatest(emailTextField.reactive.text, passwordTextField.reactive.text) { (_, _) in
      return (self.emailTextField.text?.count)! > 0 && (self.passwordTextField.text?.count)! > 0
}.bind(to: loginButton.reactive.isEnabled)

```

But i definitely would to find a way to make it work like in the example in the readme (which should be adapted I think)

**Comment by dcrobert** [comment]
combineLatest(emailTextField.reactive.text, passwordTextField.reactive.text).map { email, pass in
  return email.length > 0 && pass.length > 0
  }.bind(to: loginButton.reactive.isEnabled)

combineLatest().map <---

**Comment by omerozk** [comment]
Ok thank you that worked. I think an update of the Readme is needed.

Here the example working code for swift 4:
```
combineLatest(emailTextField.reactive.text, passwordTextField.reactive.text).map { (email, pass) -> Bool in
      return (email?.count)! > 0 && (pass?.count)! > 0
}.bind(to: loginButton.reactive.isEnabled)
```

Just a question why do we need to import Bond and ReactiveKit, shouldn't be Bond which make the link?

**Comment by dcrobert** [comment]
TBH Im not 100% positive... It looks like Bond imports ReactiveKit in itself, but the actual method for combineLatest lives in ReactiveKit.... seems strange to me as well.
