### ISSUE TITLE
Crash with MutableObservableArray removeAll()

### ISSUE THREAD

**Issue by Maxatma** [ReactiveKit/Bond#491]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert row 0 into section 0, but there are only 0 rows in section 0 after the update'

Im working with MutableObservableArray
`    var content       = MutableObservableArray<VM>()`
for tableview

I use this methods for update when uiswitch changed, so I clean 'content' and create new one
    func 
```
updateVMS(mode: switchmode) {
        content.removeAll()
        content.insert(model1VM, at: content.endIndex)
        content.insert(model2VM, at: content.endIndex)
    }
```

also in subclasses I override it, and do:

```
override func updateVMS(mode: switchmode) {
        super.updateVMS(mode: mode)
        
        switch mode {
            
        case .switchmode1:
            let switchmode1VMS = users.array.map {
                return SomeItemVM($0)            }
            content.insert(contentsOf: switchmode1VMS, at: content.endIndex)
        }
    }
```
First time it calls updateVMS  twice, but when I change switch manually, it crashes just in code string:
`        content.removeAll()
`
with issue at top, however I don't insert stuff, just trying to clear it. 
Is there anything I'm doing wrong? Any ideas how to fix? 
If I remove `content.removeAll()` code piece, it doesn't crashes

Bond 6.5.2

**Comment by dcrobert** [comment]
Can you verify that you are calling Bond's .removeAll() and not the one in Swift?

**Comment by srdanrasic** [comment]
I'm puzzled why are you doing `insert(model2VM, at: content.endIndex)` instead of `append(model2VM)`?

**Comment by dcrobert** [comment]
^^ Also True. I believe I had a similar issue and I switched to using append instead. (after questioning why I was trying to insert at the last index anyway)

**Comment by Maxatma** [comment]
Well, you can't `append(contentsOF: )` 
And Is there any diffence? I can't insert in .endIndex ?

**Comment by srdanrasic** [comment]
If this is still a problem, I would suggest batching multiple changes:

```swift
content.batchUpdate { content in 
       content.removeAll()
       content.insert(model1VM, at: content.endIndex)
       content.insert(model2VM, at: content.endIndex)
}
```
