### ISSUE TITLE
 Incorrect argument label in call (have 'where:', expected 'after:')

### ISSUE THREAD

**Issue by timothyarmes** [ReactiveKit/Bond#492]
Hi,

Since updating to the latest version of Bond, I'm now getting this error:

    Incorrect argument label in call (have 'where:', expected 'after:')

on this code:

    if let index = fcpRecentLibraries.index(where: { $0.url == url })

I can't find a new equivalent for this function. What's happened to it?

**Comment by srdanrasic** [comment]
Due to changes in Swift, ObservableArray could no longer conform to Collection protocol. It's noted on top of the readme under _Xcode 9 support._

You need to call the method on the underlying array:

```swift
if let index = fcpRecentLibraries.array.index(where: { $0.url == url })
```
