### ISSUE TITLE
Xcode 9.3 beta build failed with swift 4

### ISSUE THREAD

**Issue by zhuhuihuihui** [ReactiveKit/Bond#494]
> Type 'Observable2DArray<SectionMetadata, Item>' does not conform to protocol 'QueryableDataSourceProtocol'

Does anyone got the same issue?

**Comment by hrandeniya** [comment]
Yup, getting same issue. Any fix?

**Comment by srdanrasic** [comment]
Hey everyone,

the issue is caused by a regression in the Swift compiler: https://bugs.swift.org/browse/SR-6609.

The fix will be available in 9.3 beta 2, but I'll see if I can make a workaround in the meantime.

**Comment by srdanrasic** [comment]
Workaround is available in `swift-4.1` branch.
