### ISSUE TITLE
Table view doesn’t get updated on rebinding

### ISSUE THREAD

**Issue by mladenny** [ReactiveKit/Bond#502]
In my view controller I have
```swift
viewModel.observableObject.observeNext { [weak self] (observableObject) in
    guard let oo = observableObject else { return }
    self?.title = "№\(oo.id)"
    oo.observableArray.bind(to: self!.tableView, createCell: { (dataSource, indexPath, tableView) -> UITableViewCell in
	// cell stuff
        return cell
    }
}
```

I’m calling a service in this controller which updates the whole `observableObject` in place via `viewModel.observableObject.next(newObject)`. With breakpoints I can see that the `observableArray` has been updated but when I break inside the closure (in `// cell stuff`) it’s the previous array, before the update.

`observableArray` is of type `MutableObservable2DArray<SomeObject, AnotherObject>`.

If I pop the view controller (it `deinit`s) and open it again everything is updated.

@srdanrasic if you’d like I can give you a sample project.

**Comment by mladenny** [comment]
Here’s the sample project:
[Bond-sample.zip](https://github.com/ReactiveKit/Bond/files/1764152/Bond-sample.zip)

I’ve tried to make some clarifications with comments in the code, but I think running the project will illustrate the problem(?) well.

**Comment by srdanrasic** [comment]
It seems that you are making multiple bindings to the table view. That is not really supported so you need to dispose previous binding when making a new one.


```swift
import Bond
import ReactiveKit

var previousBindingDisposable: Disposable?

viewModel.observableObject.observeNext { [weak self] (observableObject) in
    guard let oo = observableObject else { return }
    self?.title = "№\(oo.id)"

    previousBindingDisposable?.dispose()
    previousBindingDisposable = oo.observableArray.bind(to: self!.tableView, createCell: { (dataSource, indexPath, tableView) -> UITableViewCell in
	// cell stuff
        return cell
    }
}
```

Unrelated, but will make you code cleaner: Replace observeNext with [inline binding](https://github.com/ReactiveKit/ReactiveKit#bindings).

```swift
import Bond
import ReactiveKit

var previousBindingDisposable: Disposable?

viewModel.observableObject.bind(to: self) { (me, observableObject) in
    guard let oo = observableObject else { return }
    me.title = "№\(oo.id)"

    previousBindingDisposable?.dispose()
    previousBindingDisposable = oo.observableArray.bind(to: me.tableView, createCell: { (dataSource, indexPath, tableView) -> UITableViewCell in
	// cell stuff
        return cell
    }
}
```
