### ISSUE TITLE
WatchKit

### ISSUE THREAD

**Issue by arytbk** [ReactiveKit/Bond#66]
Thanks for this great framework!
It would be nice to add support for the WatchKit UI elements...

**Comment by srdanrasic** [comment]
Thanks! That's great idea. Putting it in TODO list. I don't have much time at the moment though.

**Comment by arytbk** [comment]
Sure!

I just tried to do it myself starting with WKInterfaceLabel, however I was blocked by the fact that WatchKit properties are write only - so there is a setText but you can’t read back the current value of the text property!

For this we might need write-only Dynamic ?

**Comment by srdanrasic** [comment]
Not planned at the moment.
