### ISSUE TITLE
Add performance tests

### ISSUE THREAD

**Issue by ivanmoskalev** [ReactiveKit/Bond#87]
As this framework is designed to serve as a backbone for applications' UI layer, it is of uttermost importance to add performance tests for public functions. So far the library is time-efficient, and this efficiency has to be maintained further :)

**Comment by levous** [comment]
Great suggestion!  If you've tested it, could you contribute the first performance tests?  Im sure the project maintainers will feel more compelled to ensure those tests are automated and tracked over time if they have something to start with.

**Comment by ivanmoskalev** [comment]
@levous I'm mainly waiting for the public release of v.4, when things get stable. Otherwise @srdanrasic  will just have more tests to edit in case of restructuring the framework.
